In [1]:
from pathlib import Path
import pandas as pd
import os

DATA_DIR = Path("../data/external/kaggle/russian_financial_news")

files = sorted([file for file in DATA_DIR.rglob("*") if file.is_file()])

print("Files count:", len(files))

for file in files:
    size_mb = file.stat().st_size / 1024 / 1024
    print(f"{file.relative_to(DATA_DIR)} | {size_mb:.2f} MB")

Files count: 23
RussianFinancialNews\candles_data\10m\close.csv | 42.89 MB
RussianFinancialNews\candles_data\10m\high.csv | 42.83 MB
RussianFinancialNews\candles_data\10m\low.csv | 42.79 MB
RussianFinancialNews\candles_data\10m\open.csv | 42.93 MB
RussianFinancialNews\candles_data\10m\value.csv | 68.25 MB
RussianFinancialNews\candles_data\1d\close.csv | 0.74 MB
RussianFinancialNews\candles_data\1d\high.csv | 0.74 MB
RussianFinancialNews\candles_data\1d\low.csv | 0.73 MB
RussianFinancialNews\candles_data\1d\open.csv | 0.74 MB
RussianFinancialNews\candles_data\1d\value.csv | 1.18 MB
RussianFinancialNews\candles_data\1d\volume.csv | 0.83 MB
RussianFinancialNews\candles_data\1h\close.csv | 8.44 MB
RussianFinancialNews\candles_data\1h\high.csv | 8.42 MB
RussianFinancialNews\candles_data\1h\low.csv | 8.40 MB
RussianFinancialNews\candles_data\1h\open.csv | 8.45 MB
RussianFinancialNews\candles_data\1h\value.csv | 14.08 MB
RussianFinancialNews\candles_data\1h\volume.csv | 7.99 MB
RussianFinancialNews\news_collection.parquet | 35.79 MB
RussianFinancialNews\news_descriptions\news_collection_old.parquet | 47.36 MB
RussianFinancialNews\news_descriptions\news_description_LLama3_8b.json | 13.39 MB
RussianFinancialNews\news_descriptions\news_descriptions_GPT4o.json | 8.99 MB
RussianFinancialNews\preview.csv | 0.01 MB
RussianFinancialNews\tickers_description.json | 0.87 MB

In [2]:
csv_files = sorted(DATA_DIR.rglob("*.csv"))
json_files = sorted(DATA_DIR.rglob("*.json"))
parquet_files = sorted(DATA_DIR.rglob("*.parquet"))
xlsx_files = sorted(DATA_DIR.rglob("*.xlsx"))

print("CSV:", len(csv_files))
print("JSON:", len(json_files))
print("PARQUET:", len(parquet_files))
print("XLSX:", len(xlsx_files))

print("\nCSV files:")
for file in csv_files:
    print(file.relative_to(DATA_DIR))

CSV: 18
JSON: 3
PARQUET: 2
XLSX: 0

CSV files:
RussianFinancialNews\candles_data\10m\close.csv
RussianFinancialNews\candles_data\10m\high.csv
RussianFinancialNews\candles_data\10m\low.csv
RussianFinancialNews\candles_data\10m\open.csv
RussianFinancialNews\candles_data\10m\value.csv
RussianFinancialNews\candles_data\1d\close.csv
RussianFinancialNews\candles_data\1d\high.csv
RussianFinancialNews\candles_data\1d\low.csv
RussianFinancialNews\candles_data\1d\open.csv
RussianFinancialNews\candles_data\1d\value.csv
RussianFinancialNews\candles_data\1d\volume.csv
RussianFinancialNews\candles_data\1h\close.csv
RussianFinancialNews\candles_data\1h\high.csv
RussianFinancialNews\candles_data\1h\low.csv
RussianFinancialNews\candles_data\1h\open.csv
RussianFinancialNews\candles_data\1h\value.csv
RussianFinancialNews\candles_data\1h\volume.csv
RussianFinancialNews\preview.csv

In [3]:
for file in csv_files:
    print("\n" + "=" * 120)
    print(file.relative_to(DATA_DIR))
    
    try:
        df_sample = pd.read_csv(file, nrows=5)
        print("shape sample:", df_sample.shape)
        print("columns:", df_sample.columns.tolist())
        display(df_sample.head())
    except Exception as e:
        print("ERROR with default encoding:", e)
        
        for encoding in ["utf-8", "utf-8-sig", "cp1251"]:
            try:
                df_sample = pd.read_csv(file, nrows=5, encoding=encoding)
                print("worked encoding:", encoding)
                print("shape sample:", df_sample.shape)
                print("columns:", df_sample.columns.tolist())
                display(df_sample.head())
                break
            except Exception:
                pass

========================================================================================================================
RussianFinancialNews\candles_data\10m\close.csv
shape sample: (5, 248)
columns: ['begin', 'ABIO', 'ABRD', 'AFKS', 'AFLT', 'AKRN', 'ALRS', 'AMEZ', 'APTK', 'AQUA', 'ARSA', 'ASSB', 'ASTR', 'AVAN', 'BANE', 'BANEP', 'BELU', 'BISVP', 'BLNG', 'BRZL', 'BSPB', 'BSPBP', 'CARM', 'CBOM', 'CHGZ', 'CHKZ', 'CHMF', 'CHMK', 'CNTL', 'CNTLP', 'DELI', 'DIAS', 'DIOD', 'DSKY', 'DVEC', 'DZRD', 'DZRDP', 'EELT', 'ELFV', 'ELMT', 'ENPG', 'EUTR', 'FEES', 'FESH', 'FLOT', 'GAZA', 'GAZAP', 'GAZC', 'GAZP', 'GAZS', 'GAZT', 'GCHE', 'GECO', 'GEMA', 'GEMC', 'GMKN', 'GTRK', 'HIMCP', 'HNFG', 'HYDR', 'IGST', 'IGSTP', 'INGR', 'IRAO', 'IRKT', 'IVAT', 'JNOS', 'JNOSP', 'KAZT', 'KAZTP', 'KBSB', 'KCHE', 'KCHEP', 'KGKC', 'KGKCP', 'KLSB', 'KLVZ', 'KMAZ', 'KMEZ', 'KOGK', 'KRKN', 'KRKNP', 'KRKOP', 'KROT', 'KROTP', 'KRSB', 'KRSBP', 'KUBE', 'KUZB', 'KZOS', 'KZOSP', 'LEAS', 'LENT', 'LIFE', 'LKOH', 'LNZL', 'LNZLP', 'LPSB', 'LSNG', 'LSNGP', 'LSRG', 'LVHK', 'MAGE', 'MAGEP', 'MAGN', 'MBNK', 'MDMG', 'MFGS', 'MFGSP', 'MGKL', 'MGNT', 'MGNZ', 'MGTS', 'MGTSP', 'MISB', 'MISBP', 'MOEX', 'MRKC', 'MRKK', 'MRKP', 'MRKS', 'MRKU', 'MRKV', 'MRKY', 'MRKZ', 'MRSB', 'MSNG', 'MSRS', 'MSTT', 'MTLR', 'MTLRP', 'MTSS', 'MVID', 'NAUK', 'NFAZ', 'NKHP', 'NKNC', 'NKNCP', 'NKSH', 'NLMK', 'NMTP', 'NNSB', 'NNSBP', 'NSVZ', 'NVTK', 'OGKB', 'OMZZP', 'PAZA', 'PHOR', 'PIKK', 'PLZL', 'PMSB', 'PMSBP', 'POLY', 'POSI', 'PRFN', 'PRMB', 'RASP', 'RBCM', 'RDRB', 'RENI', 'RGSS', 'RKKE', 'RNFT', 'ROLO', 'ROSB', 'ROSN', 'ROST', 'RTGZ', 'RTKM', 'RTKMP', 'RTSB', 'RTSBP', 'RUAL', 'RUSI', 'RZSB', 'SAGO', 'SAGOP', 'SARE', 'SAREP', 'SBER', 'SBERP', 'SELG', 'SFIN', 'SGZH', 'SIBN', 'SLEN', 'SMLT', 'SNGS', 'SNGSP', 'SOFL', 'SPBE', 'STSB', 'STSBP', 'SVAV', 'SVCB', 'SVET', 'SVETP', 'TASB', 'TASBP', 'TATN', 'TATNP', 'TCSG', 'TGKA', 'TGKB', 'TGKBP', 'TGKN', 'TNSE', 'TORS', 'TORSP', 'TRMK', 'TRNFP', 'TTLK', 'TUZA', 'UGLD', 'UKUZ', 'UNAC', 'UNKL', 'UPRO', 'URKZ', 'USBN', 'UTAR', 'UWGN', 'VEON-RX', 'VGSB', 'VGSBP', 'VJGZ', 'VJGZP', 'VKCO', 'VLHZ', 'VRSB', 'VRSBP', 'VSMO', 'VSYD', 'VSYDP', 'VTBR', 'WTCM', 'WTCMP', 'WUSH', 'YAKG', 'YKEN', 'YKENP', 'YNDX', 'YRSB', 'YRSBP', 'ZAYM', 'ZILL', 'ZVEZ']

,begin,ABIO,ABRD,AFKS,AFLT,AKRN,ALRS,AMEZ,APTK,AQUA,...,WUSH,YAKG,YKEN,YKENP,YNDX,YRSB,YRSBP,ZAYM,ZILL,ZVEZ
0,2022-07-01 09:50:00,57.78,NaN,14.310,26.60,18182.0,67.49,19.855,12.366,499.0,...,NaN,110.00,NaN,NaN,1595.2,NaN,NaN,NaN,NaN,NaN
1,2022-07-01 10:00:00,56.50,172.0,14.501,26.16,18548.0,66.09,19.850,12.368,498.5,...,NaN,108.25,NaN,NaN,1572.2,NaN,NaN,NaN,2950.0,NaN
2,2022-07-01 10:10:00,56.46,172.0,14.755,26.70,18450.0,66.16,20.675,12.362,501.0,...,NaN,106.50,0.2775,NaN,1582.6,NaN,NaN,NaN,2900.0,3.545
3,2022-07-01 10:20:00,56.44,171.0,14.810,26.92,18342.0,66.18,20.005,12.424,502.5,...,NaN,105.15,NaN,NaN,1577.4,NaN,83.0,NaN,2900.0,NaN
4,2022-07-01 10:30:00,56.10,171.5,14.642,26.84,18400.0,66.10,19.885,12.394,503.0,...,NaN,105.05,NaN,NaN,1561.2,NaN,83.0,NaN,2890.0,NaN

========================================================================================================================
RussianFinancialNews\candles_data\10m\high.csv
shape sample: (5, 248)
columns: ['begin', 'ABIO', 'ABRD', 'AFKS', 'AFLT', 'AKRN', 'ALRS', 'AMEZ', 'APTK', 'AQUA', 'ARSA', 'ASSB', 'ASTR', 'AVAN', 'BANE', 'BANEP', 'BELU', 'BISVP', 'BLNG', 'BRZL', 'BSPB', 'BSPBP', 'CARM', 'CBOM', 'CHGZ', 'CHKZ', 'CHMF', 'CHMK', 'CNTL', 'CNTLP', 'DELI', 'DIAS', 'DIOD', 'DSKY', 'DVEC', 'DZRD', 'DZRDP', 'EELT', 'ELFV', 'ELMT', 'ENPG', 'EUTR', 'FEES', 'FESH', 'FLOT', 'GAZA', 'GAZAP', 'GAZC', 'GAZP', 'GAZS', 'GAZT', 'GCHE', 'GECO', 'GEMA', 'GEMC', 'GMKN', 'GTRK', 'HIMCP', 'HNFG', 'HYDR', 'IGST', 'IGSTP', 'INGR', 'IRAO', 'IRKT', 'IVAT', 'JNOS', 'JNOSP', 'KAZT', 'KAZTP', 'KBSB', 'KCHE', 'KCHEP', 'KGKC', 'KGKCP', 'KLSB', 'KLVZ', 'KMAZ', 'KMEZ', 'KOGK', 'KRKN', 'KRKNP', 'KRKOP', 'KROT', 'KROTP', 'KRSB', 'KRSBP', 'KUBE', 'KUZB', 'KZOS', 'KZOSP', 'LEAS', 'LENT', 'LIFE', 'LKOH', 'LNZL', 'LNZLP', 'LPSB', 'LSNG', 'LSNGP', 'LSRG', 'LVHK', 'MAGE', 'MAGEP', 'MAGN', 'MBNK', 'MDMG', 'MFGS', 'MFGSP', 'MGKL', 'MGNT', 'MGNZ', 'MGTS', 'MGTSP', 'MISB', 'MISBP', 'MOEX', 'MRKC', 'MRKK', 'MRKP', 'MRKS', 'MRKU', 'MRKV', 'MRKY', 'MRKZ', 'MRSB', 'MSNG', 'MSRS', 'MSTT', 'MTLR', 'MTLRP', 'MTSS', 'MVID', 'NAUK', 'NFAZ', 'NKHP', 'NKNC', 'NKNCP', 'NKSH', 'NLMK', 'NMTP', 'NNSB', 'NNSBP', 'NSVZ', 'NVTK', 'OGKB', 'OMZZP', 'PAZA', 'PHOR', 'PIKK', 'PLZL', 'PMSB', 'PMSBP', 'POLY', 'POSI', 'PRFN', 'PRMB', 'RASP', 'RBCM', 'RDRB', 'RENI', 'RGSS', 'RKKE', 'RNFT', 'ROLO', 'ROSB', 'ROSN', 'ROST', 'RTGZ', 'RTKM', 'RTKMP', 'RTSB', 'RTSBP', 'RUAL', 'RUSI', 'RZSB', 'SAGO', 'SAGOP', 'SARE', 'SAREP', 'SBER', 'SBERP', 'SELG', 'SFIN', 'SGZH', 'SIBN', 'SLEN', 'SMLT', 'SNGS', 'SNGSP', 'SOFL', 'SPBE', 'STSB', 'STSBP', 'SVAV', 'SVCB', 'SVET', 'SVETP', 'TASB', 'TASBP', 'TATN', 'TATNP', 'TCSG', 'TGKA', 'TGKB', 'TGKBP', 'TGKN', 'TNSE', 'TORS', 'TORSP', 'TRMK', 'TRNFP', 'TTLK', 'TUZA', 'UGLD', 'UKUZ', 'UNAC', 'UNKL', 'UPRO', 'URKZ', 'USBN', 'UTAR', 'UWGN', 'VEON-RX', 'VGSB', 'VGSBP', 'VJGZ', 'VJGZP', 'VKCO', 'VLHZ', 'VRSB', 'VRSBP', 'VSMO', 'VSYD', 'VSYDP', 'VTBR', 'WTCM', 'WTCMP', 'WUSH', 'YAKG', 'YKEN', 'YKENP', 'YNDX', 'YRSB', 'YRSBP', 'ZAYM', 'ZILL', 'ZVEZ']

,begin,ABIO,ABRD,AFKS,AFLT,AKRN,ALRS,AMEZ,APTK,AQUA,...,WUSH,YAKG,YKEN,YKENP,YNDX,YRSB,YRSBP,ZAYM,ZILL,ZVEZ
0,2022-07-01 09:50:00,57.78,NaN,14.310,26.60,18182.0,67.49,19.855,12.366,499.0,...,NaN,110.00,NaN,NaN,1595.2,NaN,NaN,NaN,NaN,NaN
1,2022-07-01 10:00:00,57.80,172.0,14.541,26.78,18600.0,67.48,20.395,12.450,498.5,...,NaN,110.00,NaN,NaN,1599.4,NaN,NaN,NaN,3025.0,NaN
2,2022-07-01 10:10:00,56.90,172.0,14.755,26.74,18652.0,66.35,20.800,12.414,503.0,...,NaN,107.60,0.2775,NaN,1590.0,NaN,NaN,NaN,2915.0,3.545
3,2022-07-01 10:20:00,56.58,172.0,14.870,26.94,18500.0,66.20,21.075,12.428,504.0,...,NaN,106.35,NaN,NaN,1589.8,NaN,83.0,NaN,2910.0,NaN
4,2022-07-01 10:30:00,56.46,171.5,14.810,26.96,18402.0,66.19,20.010,12.420,503.5,...,NaN,105.75,NaN,NaN,1577.2,NaN,83.0,NaN,2900.0,NaN

========================================================================================================================
RussianFinancialNews\candles_data\10m\low.csv
shape sample: (5, 248)
columns: ['begin', 'ABIO', 'ABRD', 'AFKS', 'AFLT', 'AKRN', 'ALRS', 'AMEZ', 'APTK', 'AQUA', 'ARSA', 'ASSB', 'ASTR', 'AVAN', 'BANE', 'BANEP', 'BELU', 'BISVP', 'BLNG', 'BRZL', 'BSPB', 'BSPBP', 'CARM', 'CBOM', 'CHGZ', 'CHKZ', 'CHMF', 'CHMK', 'CNTL', 'CNTLP', 'DELI', 'DIAS', 'DIOD', 'DSKY', 'DVEC', 'DZRD', 'DZRDP', 'EELT', 'ELFV', 'ELMT', 'ENPG', 'EUTR', 'FEES', 'FESH', 'FLOT', 'GAZA', 'GAZAP', 'GAZC', 'GAZP', 'GAZS', 'GAZT', 'GCHE', 'GECO', 'GEMA', 'GEMC', 'GMKN', 'GTRK', 'HIMCP', 'HNFG', 'HYDR', 'IGST', 'IGSTP', 'INGR', 'IRAO', 'IRKT', 'IVAT', 'JNOS', 'JNOSP', 'KAZT', 'KAZTP', 'KBSB', 'KCHE', 'KCHEP', 'KGKC', 'KGKCP', 'KLSB', 'KLVZ', 'KMAZ', 'KMEZ', 'KOGK', 'KRKN', 'KRKNP', 'KRKOP', 'KROT', 'KROTP', 'KRSB', 'KRSBP', 'KUBE', 'KUZB', 'KZOS', 'KZOSP', 'LEAS', 'LENT', 'LIFE', 'LKOH', 'LNZL', 'LNZLP', 'LPSB', 'LSNG', 'LSNGP', 'LSRG', 'LVHK', 'MAGE', 'MAGEP', 'MAGN', 'MBNK', 'MDMG', 'MFGS', 'MFGSP', 'MGKL', 'MGNT', 'MGNZ', 'MGTS', 'MGTSP', 'MISB', 'MISBP', 'MOEX', 'MRKC', 'MRKK', 'MRKP', 'MRKS', 'MRKU', 'MRKV', 'MRKY', 'MRKZ', 'MRSB', 'MSNG', 'MSRS', 'MSTT', 'MTLR', 'MTLRP', 'MTSS', 'MVID', 'NAUK', 'NFAZ', 'NKHP', 'NKNC', 'NKNCP', 'NKSH', 'NLMK', 'NMTP', 'NNSB', 'NNSBP', 'NSVZ', 'NVTK', 'OGKB', 'OMZZP', 'PAZA', 'PHOR', 'PIKK', 'PLZL', 'PMSB', 'PMSBP', 'POLY', 'POSI', 'PRFN', 'PRMB', 'RASP', 'RBCM', 'RDRB', 'RENI', 'RGSS', 'RKKE', 'RNFT', 'ROLO', 'ROSB', 'ROSN', 'ROST', 'RTGZ', 'RTKM', 'RTKMP', 'RTSB', 'RTSBP', 'RUAL', 'RUSI', 'RZSB', 'SAGO', 'SAGOP', 'SARE', 'SAREP', 'SBER', 'SBERP', 'SELG', 'SFIN', 'SGZH', 'SIBN', 'SLEN', 'SMLT', 'SNGS', 'SNGSP', 'SOFL', 'SPBE', 'STSB', 'STSBP', 'SVAV', 'SVCB', 'SVET', 'SVETP', 'TASB', 'TASBP', 'TATN', 'TATNP', 'TCSG', 'TGKA', 'TGKB', 'TGKBP', 'TGKN', 'TNSE', 'TORS', 'TORSP', 'TRMK', 'TRNFP', 'TTLK', 'TUZA', 'UGLD', 'UKUZ', 'UNAC', 'UNKL', 'UPRO', 'URKZ', 'USBN', 'UTAR', 'UWGN', 'VEON-RX', 'VGSB', 'VGSBP', 'VJGZ', 'VJGZP', 'VKCO', 'VLHZ', 'VRSB', 'VRSBP', 'VSMO', 'VSYD', 'VSYDP', 'VTBR', 'WTCM', 'WTCMP', 'WUSH', 'YAKG', 'YKEN', 'YKENP', 'YNDX', 'YRSB', 'YRSBP', 'ZAYM', 'ZILL', 'ZVEZ']

,begin,ABIO,ABRD,AFKS,AFLT,AKRN,ALRS,AMEZ,APTK,AQUA,...,WUSH,YAKG,YKEN,YKENP,YNDX,YRSB,YRSBP,ZAYM,ZILL,ZVEZ
0,2022-07-01 09:50:00,57.78,NaN,14.310,26.60,18182.0,67.49,19.855,12.366,499.0,...,NaN,110.00,NaN,NaN,1595.2,NaN,NaN,NaN,NaN,NaN
1,2022-07-01 10:00:00,56.22,170.5,14.200,26.02,18000.0,65.92,19.805,12.360,495.5,...,NaN,108.05,NaN,NaN,1552.0,NaN,NaN,NaN,2940.0,NaN
2,2022-07-01 10:10:00,56.22,171.0,14.520,26.10,18346.0,66.00,19.810,12.362,498.5,...,NaN,105.55,0.2775,NaN,1565.0,NaN,NaN,NaN,2895.0,3.545
3,2022-07-01 10:20:00,56.22,170.5,14.654,26.70,18300.0,65.90,19.930,12.362,500.0,...,NaN,105.15,NaN,NaN,1575.2,NaN,83.0,NaN,2890.0,NaN
4,2022-07-01 10:30:00,56.10,171.0,14.623,26.72,18328.0,66.02,19.620,12.394,500.5,...,NaN,105.05,NaN,NaN,1560.2,NaN,83.0,NaN,2890.0,NaN

========================================================================================================================
RussianFinancialNews\candles_data\10m\open.csv
shape sample: (5, 248)
columns: ['begin', 'ABIO', 'ABRD', 'AFKS', 'AFLT', 'AKRN', 'ALRS', 'AMEZ', 'APTK', 'AQUA', 'ARSA', 'ASSB', 'ASTR', 'AVAN', 'BANE', 'BANEP', 'BELU', 'BISVP', 'BLNG', 'BRZL', 'BSPB', 'BSPBP', 'CARM', 'CBOM', 'CHGZ', 'CHKZ', 'CHMF', 'CHMK', 'CNTL', 'CNTLP', 'DELI', 'DIAS', 'DIOD', 'DSKY', 'DVEC', 'DZRD', 'DZRDP', 'EELT', 'ELFV', 'ELMT', 'ENPG', 'EUTR', 'FEES', 'FESH', 'FLOT', 'GAZA', 'GAZAP', 'GAZC', 'GAZP', 'GAZS', 'GAZT', 'GCHE', 'GECO', 'GEMA', 'GEMC', 'GMKN', 'GTRK', 'HIMCP', 'HNFG', 'HYDR', 'IGST', 'IGSTP', 'INGR', 'IRAO', 'IRKT', 'IVAT', 'JNOS', 'JNOSP', 'KAZT', 'KAZTP', 'KBSB', 'KCHE', 'KCHEP', 'KGKC', 'KGKCP', 'KLSB', 'KLVZ', 'KMAZ', 'KMEZ', 'KOGK', 'KRKN', 'KRKNP', 'KRKOP', 'KROT', 'KROTP', 'KRSB', 'KRSBP', 'KUBE', 'KUZB', 'KZOS', 'KZOSP', 'LEAS', 'LENT', 'LIFE', 'LKOH', 'LNZL', 'LNZLP', 'LPSB', 'LSNG', 'LSNGP', 'LSRG', 'LVHK', 'MAGE', 'MAGEP', 'MAGN', 'MBNK', 'MDMG', 'MFGS', 'MFGSP', 'MGKL', 'MGNT', 'MGNZ', 'MGTS', 'MGTSP', 'MISB', 'MISBP', 'MOEX', 'MRKC', 'MRKK', 'MRKP', 'MRKS', 'MRKU', 'MRKV', 'MRKY', 'MRKZ', 'MRSB', 'MSNG', 'MSRS', 'MSTT', 'MTLR', 'MTLRP', 'MTSS', 'MVID', 'NAUK', 'NFAZ', 'NKHP', 'NKNC', 'NKNCP', 'NKSH', 'NLMK', 'NMTP', 'NNSB', 'NNSBP', 'NSVZ', 'NVTK', 'OGKB', 'OMZZP', 'PAZA', 'PHOR', 'PIKK', 'PLZL', 'PMSB', 'PMSBP', 'POLY', 'POSI', 'PRFN', 'PRMB', 'RASP', 'RBCM', 'RDRB', 'RENI', 'RGSS', 'RKKE', 'RNFT', 'ROLO', 'ROSB', 'ROSN', 'ROST', 'RTGZ', 'RTKM', 'RTKMP', 'RTSB', 'RTSBP', 'RUAL', 'RUSI', 'RZSB', 'SAGO', 'SAGOP', 'SARE', 'SAREP', 'SBER', 'SBERP', 'SELG', 'SFIN', 'SGZH', 'SIBN', 'SLEN', 'SMLT', 'SNGS', 'SNGSP', 'SOFL', 'SPBE', 'STSB', 'STSBP', 'SVAV', 'SVCB', 'SVET', 'SVETP', 'TASB', 'TASBP', 'TATN', 'TATNP', 'TCSG', 'TGKA', 'TGKB', 'TGKBP', 'TGKN', 'TNSE', 'TORS', 'TORSP', 'TRMK', 'TRNFP', 'TTLK', 'TUZA', 'UGLD', 'UKUZ', 'UNAC', 'UNKL', 'UPRO', 'URKZ', 'USBN', 'UTAR', 'UWGN', 'VEON-RX', 'VGSB', 'VGSBP', 'VJGZ', 'VJGZP', 'VKCO', 'VLHZ', 'VRSB', 'VRSBP', 'VSMO', 'VSYD', 'VSYDP', 'VTBR', 'WTCM', 'WTCMP', 'WUSH', 'YAKG', 'YKEN', 'YKENP', 'YNDX', 'YRSB', 'YRSBP', 'ZAYM', 'ZILL', 'ZVEZ']

,begin,ABIO,ABRD,AFKS,AFLT,AKRN,ALRS,AMEZ,APTK,AQUA,...,WUSH,YAKG,YKEN,YKENP,YNDX,YRSB,YRSBP,ZAYM,ZILL,ZVEZ
0,2022-07-01 09:50:00,57.78,NaN,14.310,26.60,18182.0,67.49,19.855,12.366,499.0,...,NaN,110.00,NaN,NaN,1595.2,NaN,NaN,NaN,NaN,NaN
1,2022-07-01 10:00:00,57.78,170.5,14.311,26.60,18022.0,67.47,20.055,12.366,497.0,...,NaN,110.00,NaN,NaN,1595.2,NaN,NaN,NaN,2940.0,NaN
2,2022-07-01 10:10:00,56.26,171.5,14.525,26.14,18532.0,66.09,19.830,12.414,498.5,...,NaN,105.95,0.2775,NaN,1572.2,NaN,NaN,NaN,2915.0,3.545
3,2022-07-01 10:20:00,56.26,172.0,14.759,26.72,18450.0,66.16,20.675,12.368,501.5,...,NaN,106.35,NaN,NaN,1582.4,NaN,83.0,NaN,2910.0,NaN
4,2022-07-01 10:30:00,56.40,171.0,14.809,26.90,18342.0,66.18,20.010,12.420,502.5,...,NaN,105.10,NaN,NaN,1577.2,NaN,83.0,NaN,2900.0,NaN

========================================================================================================================
RussianFinancialNews\candles_data\10m\value.csv
shape sample: (5, 248)
columns: ['begin', 'ABIO', 'ABRD', 'AFKS', 'AFLT', 'AKRN', 'ALRS', 'AMEZ', 'APTK', 'AQUA', 'ARSA', 'ASSB', 'ASTR', 'AVAN', 'BANE', 'BANEP', 'BELU', 'BISVP', 'BLNG', 'BRZL', 'BSPB', 'BSPBP', 'CARM', 'CBOM', 'CHGZ', 'CHKZ', 'CHMF', 'CHMK', 'CNTL', 'CNTLP', 'DELI', 'DIAS', 'DIOD', 'DSKY', 'DVEC', 'DZRD', 'DZRDP', 'EELT', 'ELFV', 'ELMT', 'ENPG', 'EUTR', 'FEES', 'FESH', 'FLOT', 'GAZA', 'GAZAP', 'GAZC', 'GAZP', 'GAZS', 'GAZT', 'GCHE', 'GECO', 'GEMA', 'GEMC', 'GMKN', 'GTRK', 'HIMCP', 'HNFG', 'HYDR', 'IGST', 'IGSTP', 'INGR', 'IRAO', 'IRKT', 'IVAT', 'JNOS', 'JNOSP', 'KAZT', 'KAZTP', 'KBSB', 'KCHE', 'KCHEP', 'KGKC', 'KGKCP', 'KLSB', 'KLVZ', 'KMAZ', 'KMEZ', 'KOGK', 'KRKN', 'KRKNP', 'KRKOP', 'KROT', 'KROTP', 'KRSB', 'KRSBP', 'KUBE', 'KUZB', 'KZOS', 'KZOSP', 'LEAS', 'LENT', 'LIFE', 'LKOH', 'LNZL', 'LNZLP', 'LPSB', 'LSNG', 'LSNGP', 'LSRG', 'LVHK', 'MAGE', 'MAGEP', 'MAGN', 'MBNK', 'MDMG', 'MFGS', 'MFGSP', 'MGKL', 'MGNT', 'MGNZ', 'MGTS', 'MGTSP', 'MISB', 'MISBP', 'MOEX', 'MRKC', 'MRKK', 'MRKP', 'MRKS', 'MRKU', 'MRKV', 'MRKY', 'MRKZ', 'MRSB', 'MSNG', 'MSRS', 'MSTT', 'MTLR', 'MTLRP', 'MTSS', 'MVID', 'NAUK', 'NFAZ', 'NKHP', 'NKNC', 'NKNCP', 'NKSH', 'NLMK', 'NMTP', 'NNSB', 'NNSBP', 'NSVZ', 'NVTK', 'OGKB', 'OMZZP', 'PAZA', 'PHOR', 'PIKK', 'PLZL', 'PMSB', 'PMSBP', 'POLY', 'POSI', 'PRFN', 'PRMB', 'RASP', 'RBCM', 'RDRB', 'RENI', 'RGSS', 'RKKE', 'RNFT', 'ROLO', 'ROSB', 'ROSN', 'ROST', 'RTGZ', 'RTKM', 'RTKMP', 'RTSB', 'RTSBP', 'RUAL', 'RUSI', 'RZSB', 'SAGO', 'SAGOP', 'SARE', 'SAREP', 'SBER', 'SBERP', 'SELG', 'SFIN', 'SGZH', 'SIBN', 'SLEN', 'SMLT', 'SNGS', 'SNGSP', 'SOFL', 'SPBE', 'STSB', 'STSBP', 'SVAV', 'SVCB', 'SVET', 'SVETP', 'TASB', 'TASBP', 'TATN', 'TATNP', 'TCSG', 'TGKA', 'TGKB', 'TGKBP', 'TGKN', 'TNSE', 'TORS', 'TORSP', 'TRMK', 'TRNFP', 'TTLK', 'TUZA', 'UGLD', 'UKUZ', 'UNAC', 'UNKL', 'UPRO', 'URKZ', 'USBN', 'UTAR', 'UWGN', 'VEON-RX', 'VGSB', 'VGSBP', 'VJGZ', 'VJGZP', 'VKCO', 'VLHZ', 'VRSB', 'VRSBP', 'VSMO', 'VSYD', 'VSYDP', 'VTBR', 'WTCM', 'WTCMP', 'WUSH', 'YAKG', 'YKEN', 'YKENP', 'YNDX', 'YRSB', 'YRSBP', 'ZAYM', 'ZILL', 'ZVEZ']

,begin,ABIO,ABRD,AFKS,AFLT,AKRN,ALRS,AMEZ,APTK,AQUA,...,WUSH,YAKG,YKEN,YKENP,YNDX,YRSB,YRSBP,ZAYM,ZILL,ZVEZ
0,2022-07-01 09:50:00,6355.8,NaN,699759.0,329042.0,90910.0,1867448.3,11913.0,4946.40,16966.0,...,NaN,154000.0,NaN,NaN,403585.6,NaN,NaN,NaN,NaN,NaN
1,2022-07-01 10:00:00,828277.6,78810.0,30870171.5,11944415.0,5530778.0,51661065.1,317837.5,114913.52,180316.0,...,NaN,568115.5,NaN,NaN,20410435.0,NaN,NaN,NaN,118240.0,NaN
2,2022-07-01 10:10:00,654231.4,123735.0,39347173.3,8538629.2,7000244.0,42341001.5,2427624.0,25127.78,519130.0,...,NaN,28595.0,2775.0,NaN,17815913.4,NaN,NaN,NaN,124760.0,3545.0
3,2022-07-01 10:20:00,257285.4,94345.0,52458518.9,6896546.0,4529040.0,39991021.9,3932660.0,29122.28,189816.5,...,NaN,12668.0,NaN,NaN,10264791.6,NaN,830.0,NaN,176735.0,NaN
4,2022-07-01 10:30:00,201755.6,34290.0,10463443.6,6396967.4,2186058.0,10338281.3,638472.0,63585.18,63842.0,...,NaN,13679.5,NaN,NaN,13437973.8,NaN,830.0,NaN,106940.0,NaN

========================================================================================================================
RussianFinancialNews\candles_data\1d\close.csv
shape sample: (5, 253)
columns: ['begin', 'ABIO', 'ABRD', 'ACKO', 'AFKS', 'AFLT', 'AGRO', 'AKRN', 'ALRS', 'AMEZ', 'APRI', 'APTK', 'AQUA', 'ARSA', 'ASSB', 'ASTR', 'AVAN', 'BANE', 'BANEP', 'BELU', 'BISVP', 'BRZL', 'BSPB', 'BSPBP', 'CARM', 'CBOM', 'CHGZ', 'CHKZ', 'CHMF', 'CHMK', 'CIAN', 'CNTL', 'CNTLP', 'DELI', 'DIAS', 'DIOD', 'DVEC', 'DZRD', 'DZRDP', 'EELT', 'ELFV', 'ELMT', 'ENPG', 'ETLN', 'EUTR', 'FEES', 'FESH', 'FIVE', 'FIXP', 'FLOT', 'GAZC', 'GAZP', 'GAZS', 'GAZT', 'GCHE', 'GECO', 'GEMA', 'GEMC', 'GLTR', 'GMKN', 'HEAD', 'HHRU', 'HIMCP', 'HNFG', 'HYDR', 'IGST', 'IGSTP', 'INGR', 'IRAO', 'IRKT', 'IVAT', 'JNOS', 'JNOSP', 'KAZT', 'KAZTP', 'KBSB', 'KCHE', 'KCHEP', 'KGKC', 'KGKCP', 'KLSB', 'KLVZ', 'KMAZ', 'KMEZ', 'KOGK', 'KRKN', 'KRKNP', 'KRKOP', 'KROT', 'KROTP', 'KRSB', 'KRSBP', 'KUBE', 'KUZB', 'KZOS', 'KZOSP', 'LEAS', 'LENT', 'LKOH', 'LNZL', 'LNZLP', 'LSNG', 'LSNGP', 'LSRG', 'LVHK', 'MAGE', 'MAGEP', 'MAGN', 'MBNK', 'MDMG', 'MFGS', 'MFGSP', 'MGKL', 'MGNT', 'MGNZ', 'MGTS', 'MGTSP', 'MISB', 'MISBP', 'MOEX', 'MRKC', 'MRKK', 'MRKP', 'MRKS', 'MRKU', 'MRKV', 'MRKY', 'MRKZ', 'MRSB', 'MSNG', 'MSRS', 'MSTT', 'MTLR', 'MTLRP', 'MTSS', 'MVID', 'NAUK', 'NFAZ', 'NKHP', 'NKNC', 'NKNCP', 'NKSH', 'NLMK', 'NMTP', 'NNSB', 'NNSBP', 'NSVZ', 'NVTK', 'OGKB', 'OKEY', 'OMZZP', 'OZON', 'PHOR', 'PIKK', 'PLZL', 'PMSB', 'PMSBP', 'POLY', 'POSI', 'PRFN', 'PRMB', 'PRMD', 'QIWI', 'RASP', 'RDRB', 'RENI', 'RGSS', 'RKKE', 'RNFT', 'ROLO', 'ROSB', 'ROSN', 'ROST', 'RTGZ', 'RTKM', 'RTKMP', 'RTSB', 'RTSBP', 'RUAL', 'RUSI', 'RZSB', 'SAGO', 'SAGOP', 'SARE', 'SAREP', 'SBER', 'SBERP', 'SELG', 'SFIN', 'SGZH', 'SIBN', 'SLEN', 'SMLT', 'SNGS', 'SNGSP', 'SOFL', 'SPBE', 'STSB', 'STSBP', 'SVAV', 'SVCB', 'SVET', 'SVETP', 'TASB', 'TASBP', 'TATN', 'TATNP', 'TCSG', 'TGKA', 'TGKB', 'TGKBP', 'TGKN', 'TNSE', 'TORS', 'TORSP', 'TRMK', 'TRNFP', 'TTLK', 'TUZA', 'UGLD', 'UKUZ', 'UNAC', 'UNKL', 'UPRO', 'URKZ', 'USBN', 'UTAR', 'VEON-RX', 'VGSB', 'VGSBP', 'VJGZ', 'VJGZP', 'VKCO', 'VLHZ', 'VRSB', 'VRSBP', 'VSEH', 'VSMO', 'VSYD', 'VSYDP', 'VTBR', 'WTCM', 'WTCMP', 'WUSH', 'YAKG', 'YDEX', 'YKEN', 'YKENP', 'YRSB', 'YRSBP', 'ZAYM', 'ZILL', 'ZVEZ']

,begin,ABIO,ABRD,ACKO,AFKS,AFLT,AGRO,AKRN,ALRS,AMEZ,...,WUSH,YAKG,YDEX,YKEN,YKENP,YRSB,YRSBP,ZAYM,ZILL,ZVEZ
0,2022-07-01,56.28,171.5,NaN,14.850,26.74,872.0,18660,66.24,21.220,...,NaN,107.00,NaN,0.282,0.2785,170.0,82.5,NaN,2920,3.500
1,2022-07-04,56.90,173.0,NaN,15.000,27.12,854.4,18422,64.55,21.895,...,NaN,109.50,NaN,0.283,0.2785,172.0,83.0,NaN,3010,3.480
2,2022-07-05,56.38,172.5,NaN,15.000,28.26,837.2,17902,64.99,21.500,...,NaN,109.20,NaN,0.273,0.2680,170.0,82.5,NaN,2950,3.470
3,2022-07-06,60.68,172.0,NaN,15.163,27.34,843.8,18088,64.96,21.325,...,NaN,107.70,NaN,0.273,0.2580,NaN,82.5,NaN,2985,3.550
4,2022-07-07,58.70,172.5,NaN,15.051,27.78,860.0,18402,65.35,21.375,...,NaN,110.45,NaN,0.269,0.2650,172.0,83.0,NaN,2900,3.605

========================================================================================================================
RussianFinancialNews\candles_data\1d\high.csv
shape sample: (5, 253)
columns: ['begin', 'ABIO', 'ABRD', 'ACKO', 'AFKS', 'AFLT', 'AGRO', 'AKRN', 'ALRS', 'AMEZ', 'APRI', 'APTK', 'AQUA', 'ARSA', 'ASSB', 'ASTR', 'AVAN', 'BANE', 'BANEP', 'BELU', 'BISVP', 'BRZL', 'BSPB', 'BSPBP', 'CARM', 'CBOM', 'CHGZ', 'CHKZ', 'CHMF', 'CHMK', 'CIAN', 'CNTL', 'CNTLP', 'DELI', 'DIAS', 'DIOD', 'DVEC', 'DZRD', 'DZRDP', 'EELT', 'ELFV', 'ELMT', 'ENPG', 'ETLN', 'EUTR', 'FEES', 'FESH', 'FIVE', 'FIXP', 'FLOT', 'GAZC', 'GAZP', 'GAZS', 'GAZT', 'GCHE', 'GECO', 'GEMA', 'GEMC', 'GLTR', 'GMKN', 'HEAD', 'HHRU', 'HIMCP', 'HNFG', 'HYDR', 'IGST', 'IGSTP', 'INGR', 'IRAO', 'IRKT', 'IVAT', 'JNOS', 'JNOSP', 'KAZT', 'KAZTP', 'KBSB', 'KCHE', 'KCHEP', 'KGKC', 'KGKCP', 'KLSB', 'KLVZ', 'KMAZ', 'KMEZ', 'KOGK', 'KRKN', 'KRKNP', 'KRKOP', 'KROT', 'KROTP', 'KRSB', 'KRSBP', 'KUBE', 'KUZB', 'KZOS', 'KZOSP', 'LEAS', 'LENT', 'LKOH', 'LNZL', 'LNZLP', 'LSNG', 'LSNGP', 'LSRG', 'LVHK', 'MAGE', 'MAGEP', 'MAGN', 'MBNK', 'MDMG', 'MFGS', 'MFGSP', 'MGKL', 'MGNT', 'MGNZ', 'MGTS', 'MGTSP', 'MISB', 'MISBP', 'MOEX', 'MRKC', 'MRKK', 'MRKP', 'MRKS', 'MRKU', 'MRKV', 'MRKY', 'MRKZ', 'MRSB', 'MSNG', 'MSRS', 'MSTT', 'MTLR', 'MTLRP', 'MTSS', 'MVID', 'NAUK', 'NFAZ', 'NKHP', 'NKNC', 'NKNCP', 'NKSH', 'NLMK', 'NMTP', 'NNSB', 'NNSBP', 'NSVZ', 'NVTK', 'OGKB', 'OKEY', 'OMZZP', 'OZON', 'PHOR', 'PIKK', 'PLZL', 'PMSB', 'PMSBP', 'POLY', 'POSI', 'PRFN', 'PRMB', 'PRMD', 'QIWI', 'RASP', 'RDRB', 'RENI', 'RGSS', 'RKKE', 'RNFT', 'ROLO', 'ROSB', 'ROSN', 'ROST', 'RTGZ', 'RTKM', 'RTKMP', 'RTSB', 'RTSBP', 'RUAL', 'RUSI', 'RZSB', 'SAGO', 'SAGOP', 'SARE', 'SAREP', 'SBER', 'SBERP', 'SELG', 'SFIN', 'SGZH', 'SIBN', 'SLEN', 'SMLT', 'SNGS', 'SNGSP', 'SOFL', 'SPBE', 'STSB', 'STSBP', 'SVAV', 'SVCB', 'SVET', 'SVETP', 'TASB', 'TASBP', 'TATN', 'TATNP', 'TCSG', 'TGKA', 'TGKB', 'TGKBP', 'TGKN', 'TNSE', 'TORS', 'TORSP', 'TRMK', 'TRNFP', 'TTLK', 'TUZA', 'UGLD', 'UKUZ', 'UNAC', 'UNKL', 'UPRO', 'URKZ', 'USBN', 'UTAR', 'VEON-RX', 'VGSB', 'VGSBP', 'VJGZ', 'VJGZP', 'VKCO', 'VLHZ', 'VRSB', 'VRSBP', 'VSEH', 'VSMO', 'VSYD', 'VSYDP', 'VTBR', 'WTCM', 'WTCMP', 'WUSH', 'YAKG', 'YDEX', 'YKEN', 'YKENP', 'YRSB', 'YRSBP', 'ZAYM', 'ZILL', 'ZVEZ']

,begin,ABIO,ABRD,ACKO,AFKS,AFLT,AGRO,AKRN,ALRS,AMEZ,...,WUSH,YAKG,YDEX,YKEN,YKENP,YRSB,YRSBP,ZAYM,ZILL,ZVEZ
0,2022-07-01,57.80,173.5,NaN,15.400,27.60,880.0,18780,67.49,22.720,...,NaN,110.00,NaN,0.2865,0.2785,172.0,83.0,NaN,3025,3.560
1,2022-07-04,59.00,174.5,NaN,15.490,27.30,888.8,18800,66.50,23.400,...,NaN,110.30,NaN,0.2900,0.2785,174.0,83.0,NaN,3095,3.590
2,2022-07-05,57.40,174.0,NaN,15.184,28.48,862.8,18520,65.20,22.500,...,NaN,110.00,NaN,0.2840,0.2700,172.0,83.0,NaN,3010,3.475
3,2022-07-06,62.38,174.5,NaN,15.228,28.48,855.0,18350,66.30,21.915,...,NaN,110.00,NaN,0.2750,0.2740,NaN,83.0,NaN,3005,3.570
4,2022-07-07,63.24,178.5,NaN,15.300,28.08,865.0,18582,65.84,21.850,...,NaN,110.85,NaN,0.2700,0.2650,172.0,83.5,NaN,2995,3.640

========================================================================================================================
RussianFinancialNews\candles_data\1d\low.csv
shape sample: (5, 253)
columns: ['begin', 'ABIO', 'ABRD', 'ACKO', 'AFKS', 'AFLT', 'AGRO', 'AKRN', 'ALRS', 'AMEZ', 'APRI', 'APTK', 'AQUA', 'ARSA', 'ASSB', 'ASTR', 'AVAN', 'BANE', 'BANEP', 'BELU', 'BISVP', 'BRZL', 'BSPB', 'BSPBP', 'CARM', 'CBOM', 'CHGZ', 'CHKZ', 'CHMF', 'CHMK', 'CIAN', 'CNTL', 'CNTLP', 'DELI', 'DIAS', 'DIOD', 'DVEC', 'DZRD', 'DZRDP', 'EELT', 'ELFV', 'ELMT', 'ENPG', 'ETLN', 'EUTR', 'FEES', 'FESH', 'FIVE', 'FIXP', 'FLOT', 'GAZC', 'GAZP', 'GAZS', 'GAZT', 'GCHE', 'GECO', 'GEMA', 'GEMC', 'GLTR', 'GMKN', 'HEAD', 'HHRU', 'HIMCP', 'HNFG', 'HYDR', 'IGST', 'IGSTP', 'INGR', 'IRAO', 'IRKT', 'IVAT', 'JNOS', 'JNOSP', 'KAZT', 'KAZTP', 'KBSB', 'KCHE', 'KCHEP', 'KGKC', 'KGKCP', 'KLSB', 'KLVZ', 'KMAZ', 'KMEZ', 'KOGK', 'KRKN', 'KRKNP', 'KRKOP', 'KROT', 'KROTP', 'KRSB', 'KRSBP', 'KUBE', 'KUZB', 'KZOS', 'KZOSP', 'LEAS', 'LENT', 'LKOH', 'LNZL', 'LNZLP', 'LSNG', 'LSNGP', 'LSRG', 'LVHK', 'MAGE', 'MAGEP', 'MAGN', 'MBNK', 'MDMG', 'MFGS', 'MFGSP', 'MGKL', 'MGNT', 'MGNZ', 'MGTS', 'MGTSP', 'MISB', 'MISBP', 'MOEX', 'MRKC', 'MRKK', 'MRKP', 'MRKS', 'MRKU', 'MRKV', 'MRKY', 'MRKZ', 'MRSB', 'MSNG', 'MSRS', 'MSTT', 'MTLR', 'MTLRP', 'MTSS', 'MVID', 'NAUK', 'NFAZ', 'NKHP', 'NKNC', 'NKNCP', 'NKSH', 'NLMK', 'NMTP', 'NNSB', 'NNSBP', 'NSVZ', 'NVTK', 'OGKB', 'OKEY', 'OMZZP', 'OZON', 'PHOR', 'PIKK', 'PLZL', 'PMSB', 'PMSBP', 'POLY', 'POSI', 'PRFN', 'PRMB', 'PRMD', 'QIWI', 'RASP', 'RDRB', 'RENI', 'RGSS', 'RKKE', 'RNFT', 'ROLO', 'ROSB', 'ROSN', 'ROST', 'RTGZ', 'RTKM', 'RTKMP', 'RTSB', 'RTSBP', 'RUAL', 'RUSI', 'RZSB', 'SAGO', 'SAGOP', 'SARE', 'SAREP', 'SBER', 'SBERP', 'SELG', 'SFIN', 'SGZH', 'SIBN', 'SLEN', 'SMLT', 'SNGS', 'SNGSP', 'SOFL', 'SPBE', 'STSB', 'STSBP', 'SVAV', 'SVCB', 'SVET', 'SVETP', 'TASB', 'TASBP', 'TATN', 'TATNP', 'TCSG', 'TGKA', 'TGKB', 'TGKBP', 'TGKN', 'TNSE', 'TORS', 'TORSP', 'TRMK', 'TRNFP', 'TTLK', 'TUZA', 'UGLD', 'UKUZ', 'UNAC', 'UNKL', 'UPRO', 'URKZ', 'USBN', 'UTAR', 'VEON-RX', 'VGSB', 'VGSBP', 'VJGZ', 'VJGZP', 'VKCO', 'VLHZ', 'VRSB', 'VRSBP', 'VSEH', 'VSMO', 'VSYD', 'VSYDP', 'VTBR', 'WTCM', 'WTCMP', 'WUSH', 'YAKG', 'YDEX', 'YKEN', 'YKENP', 'YRSB', 'YRSBP', 'ZAYM', 'ZILL', 'ZVEZ']

,begin,ABIO,ABRD,ACKO,AFKS,AFLT,AGRO,AKRN,ALRS,AMEZ,...,WUSH,YAKG,YDEX,YKEN,YKENP,YRSB,YRSBP,ZAYM,ZILL,ZVEZ
0,2022-07-01,55.86,169.5,NaN,14.200,26.02,846.0,18000,65.90,19.620,...,NaN,103.00,NaN,0.2730,0.2685,170.0,82.0,NaN,2830,3.45
1,2022-07-04,56.30,171.5,NaN,14.550,26.54,850.4,18320,64.16,20.460,...,NaN,105.50,NaN,0.2810,0.2685,172.0,82.5,NaN,2925,3.38
2,2022-07-05,55.80,171.0,NaN,14.800,26.76,811.4,17164,63.00,21.205,...,NaN,107.75,NaN,0.2685,0.2605,170.0,82.5,NaN,2895,3.43
3,2022-07-06,56.10,170.5,NaN,14.865,27.20,820.6,17502,64.67,21.210,...,NaN,107.00,NaN,0.2730,0.2580,NaN,82.5,NaN,2920,3.43
4,2022-07-07,58.02,170.0,NaN,14.760,27.26,836.0,18000,64.53,21.210,...,NaN,107.05,NaN,0.2690,0.2560,170.0,82.5,NaN,2790,3.51

========================================================================================================================
RussianFinancialNews\candles_data\1d\open.csv
shape sample: (5, 253)
columns: ['begin', 'ABIO', 'ABRD', 'ACKO', 'AFKS', 'AFLT', 'AGRO', 'AKRN', 'ALRS', 'AMEZ', 'APRI', 'APTK', 'AQUA', 'ARSA', 'ASSB', 'ASTR', 'AVAN', 'BANE', 'BANEP', 'BELU', 'BISVP', 'BRZL', 'BSPB', 'BSPBP', 'CARM', 'CBOM', 'CHGZ', 'CHKZ', 'CHMF', 'CHMK', 'CIAN', 'CNTL', 'CNTLP', 'DELI', 'DIAS', 'DIOD', 'DVEC', 'DZRD', 'DZRDP', 'EELT', 'ELFV', 'ELMT', 'ENPG', 'ETLN', 'EUTR', 'FEES', 'FESH', 'FIVE', 'FIXP', 'FLOT', 'GAZC', 'GAZP', 'GAZS', 'GAZT', 'GCHE', 'GECO', 'GEMA', 'GEMC', 'GLTR', 'GMKN', 'HEAD', 'HHRU', 'HIMCP', 'HNFG', 'HYDR', 'IGST', 'IGSTP', 'INGR', 'IRAO', 'IRKT', 'IVAT', 'JNOS', 'JNOSP', 'KAZT', 'KAZTP', 'KBSB', 'KCHE', 'KCHEP', 'KGKC', 'KGKCP', 'KLSB', 'KLVZ', 'KMAZ', 'KMEZ', 'KOGK', 'KRKN', 'KRKNP', 'KRKOP', 'KROT', 'KROTP', 'KRSB', 'KRSBP', 'KUBE', 'KUZB', 'KZOS', 'KZOSP', 'LEAS', 'LENT', 'LKOH', 'LNZL', 'LNZLP', 'LSNG', 'LSNGP', 'LSRG', 'LVHK', 'MAGE', 'MAGEP', 'MAGN', 'MBNK', 'MDMG', 'MFGS', 'MFGSP', 'MGKL', 'MGNT', 'MGNZ', 'MGTS', 'MGTSP', 'MISB', 'MISBP', 'MOEX', 'MRKC', 'MRKK', 'MRKP', 'MRKS', 'MRKU', 'MRKV', 'MRKY', 'MRKZ', 'MRSB', 'MSNG', 'MSRS', 'MSTT', 'MTLR', 'MTLRP', 'MTSS', 'MVID', 'NAUK', 'NFAZ', 'NKHP', 'NKNC', 'NKNCP', 'NKSH', 'NLMK', 'NMTP', 'NNSB', 'NNSBP', 'NSVZ', 'NVTK', 'OGKB', 'OKEY', 'OMZZP', 'OZON', 'PHOR', 'PIKK', 'PLZL', 'PMSB', 'PMSBP', 'POLY', 'POSI', 'PRFN', 'PRMB', 'PRMD', 'QIWI', 'RASP', 'RDRB', 'RENI', 'RGSS', 'RKKE', 'RNFT', 'ROLO', 'ROSB', 'ROSN', 'ROST', 'RTGZ', 'RTKM', 'RTKMP', 'RTSB', 'RTSBP', 'RUAL', 'RUSI', 'RZSB', 'SAGO', 'SAGOP', 'SARE', 'SAREP', 'SBER', 'SBERP', 'SELG', 'SFIN', 'SGZH', 'SIBN', 'SLEN', 'SMLT', 'SNGS', 'SNGSP', 'SOFL', 'SPBE', 'STSB', 'STSBP', 'SVAV', 'SVCB', 'SVET', 'SVETP', 'TASB', 'TASBP', 'TATN', 'TATNP', 'TCSG', 'TGKA', 'TGKB', 'TGKBP', 'TGKN', 'TNSE', 'TORS', 'TORSP', 'TRMK', 'TRNFP', 'TTLK', 'TUZA', 'UGLD', 'UKUZ', 'UNAC', 'UNKL', 'UPRO', 'URKZ', 'USBN', 'UTAR', 'VEON-RX', 'VGSB', 'VGSBP', 'VJGZ', 'VJGZP', 'VKCO', 'VLHZ', 'VRSB', 'VRSBP', 'VSEH', 'VSMO', 'VSYD', 'VSYDP', 'VTBR', 'WTCM', 'WTCMP', 'WUSH', 'YAKG', 'YDEX', 'YKEN', 'YKENP', 'YRSB', 'YRSBP', 'ZAYM', 'ZILL', 'ZVEZ']

,begin,ABIO,ABRD,ACKO,AFKS,AFLT,AGRO,AKRN,ALRS,AMEZ,...,WUSH,YAKG,YDEX,YKEN,YKENP,YRSB,YRSBP,ZAYM,ZILL,ZVEZ
0,2022-07-01,57.78,170.5,NaN,14.310,26.60,859.6,18182,67.49,19.855,...,NaN,110.00,NaN,0.2775,0.2700,172.0,83.0,NaN,2940,3.545
1,2022-07-04,56.30,172.5,NaN,15.000,26.80,888.8,18770,66.18,21.680,...,NaN,110.30,NaN,0.2835,0.2700,172.0,83.0,NaN,2965,3.515
2,2022-07-05,57.00,173.0,NaN,15.100,27.00,854.4,18368,64.00,21.960,...,NaN,110.00,NaN,0.2770,0.2685,172.0,83.0,NaN,3010,3.475
3,2022-07-06,56.80,173.0,NaN,14.950,28.16,824.0,17830,64.97,21.490,...,NaN,109.45,NaN,0.2745,0.2740,NaN,82.5,NaN,2955,3.430
4,2022-07-07,61.04,171.0,NaN,15.165,27.48,843.6,18000,64.99,21.315,...,NaN,107.05,NaN,0.2695,0.2560,170.0,83.0,NaN,2925,3.510

========================================================================================================================
RussianFinancialNews\candles_data\1d\value.csv
shape sample: (5, 253)
columns: ['begin', 'ABIO', 'ABRD', 'ACKO', 'AFKS', 'AFLT', 'AGRO', 'AKRN', 'ALRS', 'AMEZ', 'APRI', 'APTK', 'AQUA', 'ARSA', 'ASSB', 'ASTR', 'AVAN', 'BANE', 'BANEP', 'BELU', 'BISVP', 'BRZL', 'BSPB', 'BSPBP', 'CARM', 'CBOM', 'CHGZ', 'CHKZ', 'CHMF', 'CHMK', 'CIAN', 'CNTL', 'CNTLP', 'DELI', 'DIAS', 'DIOD', 'DVEC', 'DZRD', 'DZRDP', 'EELT', 'ELFV', 'ELMT', 'ENPG', 'ETLN', 'EUTR', 'FEES', 'FESH', 'FIVE', 'FIXP', 'FLOT', 'GAZC', 'GAZP', 'GAZS', 'GAZT', 'GCHE', 'GECO', 'GEMA', 'GEMC', 'GLTR', 'GMKN', 'HEAD', 'HHRU', 'HIMCP', 'HNFG', 'HYDR', 'IGST', 'IGSTP', 'INGR', 'IRAO', 'IRKT', 'IVAT', 'JNOS', 'JNOSP', 'KAZT', 'KAZTP', 'KBSB', 'KCHE', 'KCHEP', 'KGKC', 'KGKCP', 'KLSB', 'KLVZ', 'KMAZ', 'KMEZ', 'KOGK', 'KRKN', 'KRKNP', 'KRKOP', 'KROT', 'KROTP', 'KRSB', 'KRSBP', 'KUBE', 'KUZB', 'KZOS', 'KZOSP', 'LEAS', 'LENT', 'LKOH', 'LNZL', 'LNZLP', 'LSNG', 'LSNGP', 'LSRG', 'LVHK', 'MAGE', 'MAGEP', 'MAGN', 'MBNK', 'MDMG', 'MFGS', 'MFGSP', 'MGKL', 'MGNT', 'MGNZ', 'MGTS', 'MGTSP', 'MISB', 'MISBP', 'MOEX', 'MRKC', 'MRKK', 'MRKP', 'MRKS', 'MRKU', 'MRKV', 'MRKY', 'MRKZ', 'MRSB', 'MSNG', 'MSRS', 'MSTT', 'MTLR', 'MTLRP', 'MTSS', 'MVID', 'NAUK', 'NFAZ', 'NKHP', 'NKNC', 'NKNCP', 'NKSH', 'NLMK', 'NMTP', 'NNSB', 'NNSBP', 'NSVZ', 'NVTK', 'OGKB', 'OKEY', 'OMZZP', 'OZON', 'PHOR', 'PIKK', 'PLZL', 'PMSB', 'PMSBP', 'POLY', 'POSI', 'PRFN', 'PRMB', 'PRMD', 'QIWI', 'RASP', 'RDRB', 'RENI', 'RGSS', 'RKKE', 'RNFT', 'ROLO', 'ROSB', 'ROSN', 'ROST', 'RTGZ', 'RTKM', 'RTKMP', 'RTSB', 'RTSBP', 'RUAL', 'RUSI', 'RZSB', 'SAGO', 'SAGOP', 'SARE', 'SAREP', 'SBER', 'SBERP', 'SELG', 'SFIN', 'SGZH', 'SIBN', 'SLEN', 'SMLT', 'SNGS', 'SNGSP', 'SOFL', 'SPBE', 'STSB', 'STSBP', 'SVAV', 'SVCB', 'SVET', 'SVETP', 'TASB', 'TASBP', 'TATN', 'TATNP', 'TCSG', 'TGKA', 'TGKB', 'TGKBP', 'TGKN', 'TNSE', 'TORS', 'TORSP', 'TRMK', 'TRNFP', 'TTLK', 'TUZA', 'UGLD', 'UKUZ', 'UNAC', 'UNKL', 'UPRO', 'URKZ', 'USBN', 'UTAR', 'VEON-RX', 'VGSB', 'VGSBP', 'VJGZ', 'VJGZP', 'VKCO', 'VLHZ', 'VRSB', 'VRSBP', 'VSEH', 'VSMO', 'VSYD', 'VSYDP', 'VTBR', 'WTCM', 'WTCMP', 'WUSH', 'YAKG', 'YDEX', 'YKEN', 'YKENP', 'YRSB', 'YRSBP', 'ZAYM', 'ZILL', 'ZVEZ']

,begin,ABIO,ABRD,ACKO,AFKS,AFLT,AGRO,AKRN,ALRS,AMEZ,...,WUSH,YAKG,YDEX,YKEN,YKENP,YRSB,YRSBP,ZAYM,ZILL,ZVEZ
0,2022-07-01,9061161.0,3371415,NaN,800070134.3,135396783.4,43947286.4,102197744,841793004.8,63526780.0,...,NaN,4842215.5,NaN,58550,13650,10240.0,30435,NaN,1472265,171825
1,2022-07-04,11274502.2,3139485,NaN,504082601.1,109467642.6,47796858.4,101970336,573081202.9,83929642.5,...,NaN,2129976.0,NaN,79785,38505,18960.0,11595,NaN,1912220,714080
2,2022-07-05,7487469.0,2981070,NaN,250439785.4,181704169.8,63770578.8,195810230,695797460.8,8803550.5,...,NaN,1219360.0,NaN,139495,74310,15320.0,4145,NaN,658095,106685
3,2022-07-06,55416892.8,5011205,NaN,371256364.6,218575765.2,45364247.6,87735742,563219863.8,4254449.0,...,NaN,1481268.5,NaN,76860,53265,NaN,4970,NaN,1519170,214195
4,2022-07-07,24377859.4,5390310,NaN,375531923.6,227550993.4,26555784.2,90460100,280164315.8,4110041.5,...,NaN,3706630.0,NaN,37725,28765,3420.0,12450,NaN,2837500,186955

========================================================================================================================
RussianFinancialNews\candles_data\1d\volume.csv
shape sample: (5, 253)
columns: ['begin', 'ABIO', 'ABRD', 'ACKO', 'AFKS', 'AFLT', 'AGRO', 'AKRN', 'ALRS', 'AMEZ', 'APRI', 'APTK', 'AQUA', 'ARSA', 'ASSB', 'ASTR', 'AVAN', 'BANE', 'BANEP', 'BELU', 'BISVP', 'BRZL', 'BSPB', 'BSPBP', 'CARM', 'CBOM', 'CHGZ', 'CHKZ', 'CHMF', 'CHMK', 'CIAN', 'CNTL', 'CNTLP', 'DELI', 'DIAS', 'DIOD', 'DVEC', 'DZRD', 'DZRDP', 'EELT', 'ELFV', 'ELMT', 'ENPG', 'ETLN', 'EUTR', 'FEES', 'FESH', 'FIVE', 'FIXP', 'FLOT', 'GAZC', 'GAZP', 'GAZS', 'GAZT', 'GCHE', 'GECO', 'GEMA', 'GEMC', 'GLTR', 'GMKN', 'HEAD', 'HHRU', 'HIMCP', 'HNFG', 'HYDR', 'IGST', 'IGSTP', 'INGR', 'IRAO', 'IRKT', 'IVAT', 'JNOS', 'JNOSP', 'KAZT', 'KAZTP', 'KBSB', 'KCHE', 'KCHEP', 'KGKC', 'KGKCP', 'KLSB', 'KLVZ', 'KMAZ', 'KMEZ', 'KOGK', 'KRKN', 'KRKNP', 'KRKOP', 'KROT', 'KROTP', 'KRSB', 'KRSBP', 'KUBE', 'KUZB', 'KZOS', 'KZOSP', 'LEAS', 'LENT', 'LKOH', 'LNZL', 'LNZLP', 'LSNG', 'LSNGP', 'LSRG', 'LVHK', 'MAGE', 'MAGEP', 'MAGN', 'MBNK', 'MDMG', 'MFGS', 'MFGSP', 'MGKL', 'MGNT', 'MGNZ', 'MGTS', 'MGTSP', 'MISB', 'MISBP', 'MOEX', 'MRKC', 'MRKK', 'MRKP', 'MRKS', 'MRKU', 'MRKV', 'MRKY', 'MRKZ', 'MRSB', 'MSNG', 'MSRS', 'MSTT', 'MTLR', 'MTLRP', 'MTSS', 'MVID', 'NAUK', 'NFAZ', 'NKHP', 'NKNC', 'NKNCP', 'NKSH', 'NLMK', 'NMTP', 'NNSB', 'NNSBP', 'NSVZ', 'NVTK', 'OGKB', 'OKEY', 'OMZZP', 'OZON', 'PHOR', 'PIKK', 'PLZL', 'PMSB', 'PMSBP', 'POLY', 'POSI', 'PRFN', 'PRMB', 'PRMD', 'QIWI', 'RASP', 'RDRB', 'RENI', 'RGSS', 'RKKE', 'RNFT', 'ROLO', 'ROSB', 'ROSN', 'ROST', 'RTGZ', 'RTKM', 'RTKMP', 'RTSB', 'RTSBP', 'RUAL', 'RUSI', 'RZSB', 'SAGO', 'SAGOP', 'SARE', 'SAREP', 'SBER', 'SBERP', 'SELG', 'SFIN', 'SGZH', 'SIBN', 'SLEN', 'SMLT', 'SNGS', 'SNGSP', 'SOFL', 'SPBE', 'STSB', 'STSBP', 'SVAV', 'SVCB', 'SVET', 'SVETP', 'TASB', 'TASBP', 'TATN', 'TATNP', 'TCSG', 'TGKA', 'TGKB', 'TGKBP', 'TGKN', 'TNSE', 'TORS', 'TORSP', 'TRMK', 'TRNFP', 'TTLK', 'TUZA', 'UGLD', 'UKUZ', 'UNAC', 'UNKL', 'UPRO', 'URKZ', 'USBN', 'UTAR', 'VEON-RX', 'VGSB', 'VGSBP', 'VJGZ', 'VJGZP', 'VKCO', 'VLHZ', 'VRSB', 'VRSBP', 'VSEH', 'VSMO', 'VSYD', 'VSYDP', 'VTBR', 'WTCM', 'WTCMP', 'WUSH', 'YAKG', 'YDEX', 'YKEN', 'YKENP', 'YRSB', 'YRSBP', 'ZAYM', 'ZILL', 'ZVEZ']

,begin,ABIO,ABRD,ACKO,AFKS,AFLT,AGRO,AKRN,ALRS,AMEZ,...,WUSH,YAKG,YDEX,YKEN,YKENP,YRSB,YRSBP,ZAYM,ZILL,ZVEZ
0,2022-07-01,160420,19710,NaN,53505600,5024590,50931,5509,12684950,3026900,...,NaN,45270,NaN,210000,50000,60.0,370,NaN,505,49000
1,2022-07-04,196480,18120,NaN,33622200,4064180,55832,5494,8783000,3819200,...,NaN,19590,NaN,280000,140000,110.0,140,NaN,640,205000
2,2022-07-05,132520,17280,NaN,16783300,6616650,76156,11058,10855380,406100,...,NaN,11150,NaN,510000,280000,90.0,50,NaN,225,31000
3,2022-07-06,919000,29070,NaN,24618400,7856010,53610,4891,8599300,198500,...,NaN,13720,NaN,280000,200000,NaN,60,NaN,507,61000
4,2022-07-07,400380,31220,NaN,25025000,8173990,30944,4901,4289460,191600,...,NaN,33840,NaN,140000,110000,20.0,150,NaN,997,52000

========================================================================================================================
RussianFinancialNews\candles_data\1h\close.csv
shape sample: (5, 253)
columns: ['begin', 'ABIO', 'ABRD', 'ACKO', 'AFKS', 'AFLT', 'AGRO', 'AKRN', 'ALRS', 'AMEZ', 'APRI', 'APTK', 'AQUA', 'ARSA', 'ASSB', 'ASTR', 'AVAN', 'BANE', 'BANEP', 'BELU', 'BISVP', 'BRZL', 'BSPB', 'BSPBP', 'CARM', 'CBOM', 'CHGZ', 'CHKZ', 'CHMF', 'CHMK', 'CIAN', 'CNTL', 'CNTLP', 'DELI', 'DIAS', 'DIOD', 'DVEC', 'DZRD', 'DZRDP', 'EELT', 'ELFV', 'ELMT', 'ENPG', 'ETLN', 'EUTR', 'FEES', 'FESH', 'FIVE', 'FIXP', 'FLOT', 'GAZC', 'GAZP', 'GAZS', 'GAZT', 'GCHE', 'GECO', 'GEMA', 'GEMC', 'GLTR', 'GMKN', 'HEAD', 'HHRU', 'HIMCP', 'HNFG', 'HYDR', 'IGST', 'IGSTP', 'INGR', 'IRAO', 'IRKT', 'IVAT', 'JNOS', 'JNOSP', 'KAZT', 'KAZTP', 'KBSB', 'KCHE', 'KCHEP', 'KGKC', 'KGKCP', 'KLSB', 'KLVZ', 'KMAZ', 'KMEZ', 'KOGK', 'KRKN', 'KRKNP', 'KRKOP', 'KROT', 'KROTP', 'KRSB', 'KRSBP', 'KUBE', 'KUZB', 'KZOS', 'KZOSP', 'LEAS', 'LENT', 'LKOH', 'LNZL', 'LNZLP', 'LSNG', 'LSNGP', 'LSRG', 'LVHK', 'MAGE', 'MAGEP', 'MAGN', 'MBNK', 'MDMG', 'MFGS', 'MFGSP', 'MGKL', 'MGNT', 'MGNZ', 'MGTS', 'MGTSP', 'MISB', 'MISBP', 'MOEX', 'MRKC', 'MRKK', 'MRKP', 'MRKS', 'MRKU', 'MRKV', 'MRKY', 'MRKZ', 'MRSB', 'MSNG', 'MSRS', 'MSTT', 'MTLR', 'MTLRP', 'MTSS', 'MVID', 'NAUK', 'NFAZ', 'NKHP', 'NKNC', 'NKNCP', 'NKSH', 'NLMK', 'NMTP', 'NNSB', 'NNSBP', 'NSVZ', 'NVTK', 'OGKB', 'OKEY', 'OMZZP', 'OZON', 'PHOR', 'PIKK', 'PLZL', 'PMSB', 'PMSBP', 'POLY', 'POSI', 'PRFN', 'PRMB', 'PRMD', 'QIWI', 'RASP', 'RDRB', 'RENI', 'RGSS', 'RKKE', 'RNFT', 'ROLO', 'ROSB', 'ROSN', 'ROST', 'RTGZ', 'RTKM', 'RTKMP', 'RTSB', 'RTSBP', 'RUAL', 'RUSI', 'RZSB', 'SAGO', 'SAGOP', 'SARE', 'SAREP', 'SBER', 'SBERP', 'SELG', 'SFIN', 'SGZH', 'SIBN', 'SLEN', 'SMLT', 'SNGS', 'SNGSP', 'SOFL', 'SPBE', 'STSB', 'STSBP', 'SVAV', 'SVCB', 'SVET', 'SVETP', 'TASB', 'TASBP', 'TATN', 'TATNP', 'TCSG', 'TGKA', 'TGKB', 'TGKBP', 'TGKN', 'TNSE', 'TORS', 'TORSP', 'TRMK', 'TRNFP', 'TTLK', 'TUZA', 'UGLD', 'UKUZ', 'UNAC', 'UNKL', 'UPRO', 'URKZ', 'USBN', 'UTAR', 'VEON-RX', 'VGSB', 'VGSBP', 'VJGZ', 'VJGZP', 'VKCO', 'VLHZ', 'VRSB', 'VRSBP', 'VSEH', 'VSMO', 'VSYD', 'VSYDP', 'VTBR', 'WTCM', 'WTCMP', 'WUSH', 'YAKG', 'YDEX', 'YKEN', 'YKENP', 'YRSB', 'YRSBP', 'ZAYM', 'ZILL', 'ZVEZ']

,begin,ABIO,ABRD,ACKO,AFKS,AFLT,AGRO,AKRN,ALRS,AMEZ,...,WUSH,YAKG,YDEX,YKEN,YKENP,YRSB,YRSBP,ZAYM,ZILL,ZVEZ
0,2022-07-01 09:00:00,57.78,NaN,NaN,14.310,26.60,859.6,18182,67.49,19.855,...,NaN,110.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2022-07-01 10:00:00,56.40,171.5,NaN,14.755,26.76,865.4,18396,66.29,19.830,...,NaN,104.25,NaN,0.2775,NaN,NaN,83.0,NaN,2890.0,3.560
2,2022-07-01 11:00:00,56.36,169.5,NaN,14.793,27.44,860.0,18500,66.20,19.750,...,NaN,103.20,NaN,NaN,NaN,172.0,82.5,NaN,2925.0,3.560
3,2022-07-01 12:00:00,56.92,171.0,NaN,15.133,27.20,863.0,18526,66.34,19.750,...,NaN,106.15,NaN,NaN,NaN,NaN,NaN,NaN,2915.0,NaN
4,2022-07-01 13:00:00,56.18,172.0,NaN,15.213,27.18,859.8,18594,66.18,19.980,...,NaN,104.80,NaN,NaN,NaN,NaN,NaN,NaN,2930.0,3.545

========================================================================================================================
RussianFinancialNews\candles_data\1h\high.csv
shape sample: (5, 253)
columns: ['begin', 'ABIO', 'ABRD', 'ACKO', 'AFKS', 'AFLT', 'AGRO', 'AKRN', 'ALRS', 'AMEZ', 'APRI', 'APTK', 'AQUA', 'ARSA', 'ASSB', 'ASTR', 'AVAN', 'BANE', 'BANEP', 'BELU', 'BISVP', 'BRZL', 'BSPB', 'BSPBP', 'CARM', 'CBOM', 'CHGZ', 'CHKZ', 'CHMF', 'CHMK', 'CIAN', 'CNTL', 'CNTLP', 'DELI', 'DIAS', 'DIOD', 'DVEC', 'DZRD', 'DZRDP', 'EELT', 'ELFV', 'ELMT', 'ENPG', 'ETLN', 'EUTR', 'FEES', 'FESH', 'FIVE', 'FIXP', 'FLOT', 'GAZC', 'GAZP', 'GAZS', 'GAZT', 'GCHE', 'GECO', 'GEMA', 'GEMC', 'GLTR', 'GMKN', 'HEAD', 'HHRU', 'HIMCP', 'HNFG', 'HYDR', 'IGST', 'IGSTP', 'INGR', 'IRAO', 'IRKT', 'IVAT', 'JNOS', 'JNOSP', 'KAZT', 'KAZTP', 'KBSB', 'KCHE', 'KCHEP', 'KGKC', 'KGKCP', 'KLSB', 'KLVZ', 'KMAZ', 'KMEZ', 'KOGK', 'KRKN', 'KRKNP', 'KRKOP', 'KROT', 'KROTP', 'KRSB', 'KRSBP', 'KUBE', 'KUZB', 'KZOS', 'KZOSP', 'LEAS', 'LENT', 'LKOH', 'LNZL', 'LNZLP', 'LSNG', 'LSNGP', 'LSRG', 'LVHK', 'MAGE', 'MAGEP', 'MAGN', 'MBNK', 'MDMG', 'MFGS', 'MFGSP', 'MGKL', 'MGNT', 'MGNZ', 'MGTS', 'MGTSP', 'MISB', 'MISBP', 'MOEX', 'MRKC', 'MRKK', 'MRKP', 'MRKS', 'MRKU', 'MRKV', 'MRKY', 'MRKZ', 'MRSB', 'MSNG', 'MSRS', 'MSTT', 'MTLR', 'MTLRP', 'MTSS', 'MVID', 'NAUK', 'NFAZ', 'NKHP', 'NKNC', 'NKNCP', 'NKSH', 'NLMK', 'NMTP', 'NNSB', 'NNSBP', 'NSVZ', 'NVTK', 'OGKB', 'OKEY', 'OMZZP', 'OZON', 'PHOR', 'PIKK', 'PLZL', 'PMSB', 'PMSBP', 'POLY', 'POSI', 'PRFN', 'PRMB', 'PRMD', 'QIWI', 'RASP', 'RDRB', 'RENI', 'RGSS', 'RKKE', 'RNFT', 'ROLO', 'ROSB', 'ROSN', 'ROST', 'RTGZ', 'RTKM', 'RTKMP', 'RTSB', 'RTSBP', 'RUAL', 'RUSI', 'RZSB', 'SAGO', 'SAGOP', 'SARE', 'SAREP', 'SBER', 'SBERP', 'SELG', 'SFIN', 'SGZH', 'SIBN', 'SLEN', 'SMLT', 'SNGS', 'SNGSP', 'SOFL', 'SPBE', 'STSB', 'STSBP', 'SVAV', 'SVCB', 'SVET', 'SVETP', 'TASB', 'TASBP', 'TATN', 'TATNP', 'TCSG', 'TGKA', 'TGKB', 'TGKBP', 'TGKN', 'TNSE', 'TORS', 'TORSP', 'TRMK', 'TRNFP', 'TTLK', 'TUZA', 'UGLD', 'UKUZ', 'UNAC', 'UNKL', 'UPRO', 'URKZ', 'USBN', 'UTAR', 'VEON-RX', 'VGSB', 'VGSBP', 'VJGZ', 'VJGZP', 'VKCO', 'VLHZ', 'VRSB', 'VRSBP', 'VSEH', 'VSMO', 'VSYD', 'VSYDP', 'VTBR', 'WTCM', 'WTCMP', 'WUSH', 'YAKG', 'YDEX', 'YKEN', 'YKENP', 'YRSB', 'YRSBP', 'ZAYM', 'ZILL', 'ZVEZ']

,begin,ABIO,ABRD,ACKO,AFKS,AFLT,AGRO,AKRN,ALRS,AMEZ,...,WUSH,YAKG,YDEX,YKEN,YKENP,YRSB,YRSBP,ZAYM,ZILL,ZVEZ
0,2022-07-01 09:00:00,57.78,NaN,NaN,14.310,26.60,859.6,18182,67.49,19.855,...,NaN,110.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2022-07-01 10:00:00,57.80,172.0,NaN,14.870,26.96,880.0,18652,67.48,21.075,...,NaN,110.00,NaN,0.2775,NaN,NaN,83.0,NaN,3025.0,3.560
2,2022-07-01 11:00:00,56.50,171.5,NaN,14.879,27.46,869.0,18500,66.29,19.835,...,NaN,105.05,NaN,NaN,NaN,172.0,82.5,NaN,2925.0,3.560
3,2022-07-01 12:00:00,57.00,171.5,NaN,15.280,27.60,863.8,18780,66.45,19.750,...,NaN,106.90,NaN,NaN,NaN,NaN,NaN,NaN,2915.0,NaN
4,2022-07-01 13:00:00,57.10,172.0,NaN,15.240,27.24,863.0,18600,66.44,19.985,...,NaN,106.10,NaN,NaN,NaN,NaN,NaN,NaN,2930.0,3.545

========================================================================================================================
RussianFinancialNews\candles_data\1h\low.csv
shape sample: (5, 253)
columns: ['begin', 'ABIO', 'ABRD', 'ACKO', 'AFKS', 'AFLT', 'AGRO', 'AKRN', 'ALRS', 'AMEZ', 'APRI', 'APTK', 'AQUA', 'ARSA', 'ASSB', 'ASTR', 'AVAN', 'BANE', 'BANEP', 'BELU', 'BISVP', 'BRZL', 'BSPB', 'BSPBP', 'CARM', 'CBOM', 'CHGZ', 'CHKZ', 'CHMF', 'CHMK', 'CIAN', 'CNTL', 'CNTLP', 'DELI', 'DIAS', 'DIOD', 'DVEC', 'DZRD', 'DZRDP', 'EELT', 'ELFV', 'ELMT', 'ENPG', 'ETLN', 'EUTR', 'FEES', 'FESH', 'FIVE', 'FIXP', 'FLOT', 'GAZC', 'GAZP', 'GAZS', 'GAZT', 'GCHE', 'GECO', 'GEMA', 'GEMC', 'GLTR', 'GMKN', 'HEAD', 'HHRU', 'HIMCP', 'HNFG', 'HYDR', 'IGST', 'IGSTP', 'INGR', 'IRAO', 'IRKT', 'IVAT', 'JNOS', 'JNOSP', 'KAZT', 'KAZTP', 'KBSB', 'KCHE', 'KCHEP', 'KGKC', 'KGKCP', 'KLSB', 'KLVZ', 'KMAZ', 'KMEZ', 'KOGK', 'KRKN', 'KRKNP', 'KRKOP', 'KROT', 'KROTP', 'KRSB', 'KRSBP', 'KUBE', 'KUZB', 'KZOS', 'KZOSP', 'LEAS', 'LENT', 'LKOH', 'LNZL', 'LNZLP', 'LSNG', 'LSNGP', 'LSRG', 'LVHK', 'MAGE', 'MAGEP', 'MAGN', 'MBNK', 'MDMG', 'MFGS', 'MFGSP', 'MGKL', 'MGNT', 'MGNZ', 'MGTS', 'MGTSP', 'MISB', 'MISBP', 'MOEX', 'MRKC', 'MRKK', 'MRKP', 'MRKS', 'MRKU', 'MRKV', 'MRKY', 'MRKZ', 'MRSB', 'MSNG', 'MSRS', 'MSTT', 'MTLR', 'MTLRP', 'MTSS', 'MVID', 'NAUK', 'NFAZ', 'NKHP', 'NKNC', 'NKNCP', 'NKSH', 'NLMK', 'NMTP', 'NNSB', 'NNSBP', 'NSVZ', 'NVTK', 'OGKB', 'OKEY', 'OMZZP', 'OZON', 'PHOR', 'PIKK', 'PLZL', 'PMSB', 'PMSBP', 'POLY', 'POSI', 'PRFN', 'PRMB', 'PRMD', 'QIWI', 'RASP', 'RDRB', 'RENI', 'RGSS', 'RKKE', 'RNFT', 'ROLO', 'ROSB', 'ROSN', 'ROST', 'RTGZ', 'RTKM', 'RTKMP', 'RTSB', 'RTSBP', 'RUAL', 'RUSI', 'RZSB', 'SAGO', 'SAGOP', 'SARE', 'SAREP', 'SBER', 'SBERP', 'SELG', 'SFIN', 'SGZH', 'SIBN', 'SLEN', 'SMLT', 'SNGS', 'SNGSP', 'SOFL', 'SPBE', 'STSB', 'STSBP', 'SVAV', 'SVCB', 'SVET', 'SVETP', 'TASB', 'TASBP', 'TATN', 'TATNP', 'TCSG', 'TGKA', 'TGKB', 'TGKBP', 'TGKN', 'TNSE', 'TORS', 'TORSP', 'TRMK', 'TRNFP', 'TTLK', 'TUZA', 'UGLD', 'UKUZ', 'UNAC', 'UNKL', 'UPRO', 'URKZ', 'USBN', 'UTAR', 'VEON-RX', 'VGSB', 'VGSBP', 'VJGZ', 'VJGZP', 'VKCO', 'VLHZ', 'VRSB', 'VRSBP', 'VSEH', 'VSMO', 'VSYD', 'VSYDP', 'VTBR', 'WTCM', 'WTCMP', 'WUSH', 'YAKG', 'YDEX', 'YKEN', 'YKENP', 'YRSB', 'YRSBP', 'ZAYM', 'ZILL', 'ZVEZ']

,begin,ABIO,ABRD,ACKO,AFKS,AFLT,AGRO,AKRN,ALRS,AMEZ,...,WUSH,YAKG,YDEX,YKEN,YKENP,YRSB,YRSBP,ZAYM,ZILL,ZVEZ
0,2022-07-01 09:00:00,57.78,NaN,NaN,14.310,26.60,859.6,18182,67.49,19.855,...,NaN,110.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2022-07-01 10:00:00,56.04,170.5,NaN,14.200,26.02,846.0,18000,65.90,19.620,...,NaN,103.00,NaN,0.2775,NaN,NaN,83.0,NaN,2890.0,3.545
2,2022-07-01 11:00:00,56.12,169.5,NaN,14.750,26.64,858.0,18270,66.06,19.620,...,NaN,103.05,NaN,NaN,NaN,172.0,82.0,NaN,2890.0,3.560
3,2022-07-01 12:00:00,56.20,170.0,NaN,14.791,27.08,855.8,18484,66.10,19.730,...,NaN,104.80,NaN,NaN,NaN,NaN,NaN,NaN,2915.0,NaN
4,2022-07-01 13:00:00,55.86,170.0,NaN,15.001,27.04,858.0,18522,66.12,19.730,...,NaN,104.80,NaN,NaN,NaN,NaN,NaN,NaN,2925.0,3.495

========================================================================================================================
RussianFinancialNews\candles_data\1h\open.csv
shape sample: (5, 253)
columns: ['begin', 'ABIO', 'ABRD', 'ACKO', 'AFKS', 'AFLT', 'AGRO', 'AKRN', 'ALRS', 'AMEZ', 'APRI', 'APTK', 'AQUA', 'ARSA', 'ASSB', 'ASTR', 'AVAN', 'BANE', 'BANEP', 'BELU', 'BISVP', 'BRZL', 'BSPB', 'BSPBP', 'CARM', 'CBOM', 'CHGZ', 'CHKZ', 'CHMF', 'CHMK', 'CIAN', 'CNTL', 'CNTLP', 'DELI', 'DIAS', 'DIOD', 'DVEC', 'DZRD', 'DZRDP', 'EELT', 'ELFV', 'ELMT', 'ENPG', 'ETLN', 'EUTR', 'FEES', 'FESH', 'FIVE', 'FIXP', 'FLOT', 'GAZC', 'GAZP', 'GAZS', 'GAZT', 'GCHE', 'GECO', 'GEMA', 'GEMC', 'GLTR', 'GMKN', 'HEAD', 'HHRU', 'HIMCP', 'HNFG', 'HYDR', 'IGST', 'IGSTP', 'INGR', 'IRAO', 'IRKT', 'IVAT', 'JNOS', 'JNOSP', 'KAZT', 'KAZTP', 'KBSB', 'KCHE', 'KCHEP', 'KGKC', 'KGKCP', 'KLSB', 'KLVZ', 'KMAZ', 'KMEZ', 'KOGK', 'KRKN', 'KRKNP', 'KRKOP', 'KROT', 'KROTP', 'KRSB', 'KRSBP', 'KUBE', 'KUZB', 'KZOS', 'KZOSP', 'LEAS', 'LENT', 'LKOH', 'LNZL', 'LNZLP', 'LSNG', 'LSNGP', 'LSRG', 'LVHK', 'MAGE', 'MAGEP', 'MAGN', 'MBNK', 'MDMG', 'MFGS', 'MFGSP', 'MGKL', 'MGNT', 'MGNZ', 'MGTS', 'MGTSP', 'MISB', 'MISBP', 'MOEX', 'MRKC', 'MRKK', 'MRKP', 'MRKS', 'MRKU', 'MRKV', 'MRKY', 'MRKZ', 'MRSB', 'MSNG', 'MSRS', 'MSTT', 'MTLR', 'MTLRP', 'MTSS', 'MVID', 'NAUK', 'NFAZ', 'NKHP', 'NKNC', 'NKNCP', 'NKSH', 'NLMK', 'NMTP', 'NNSB', 'NNSBP', 'NSVZ', 'NVTK', 'OGKB', 'OKEY', 'OMZZP', 'OZON', 'PHOR', 'PIKK', 'PLZL', 'PMSB', 'PMSBP', 'POLY', 'POSI', 'PRFN', 'PRMB', 'PRMD', 'QIWI', 'RASP', 'RDRB', 'RENI', 'RGSS', 'RKKE', 'RNFT', 'ROLO', 'ROSB', 'ROSN', 'ROST', 'RTGZ', 'RTKM', 'RTKMP', 'RTSB', 'RTSBP', 'RUAL', 'RUSI', 'RZSB', 'SAGO', 'SAGOP', 'SARE', 'SAREP', 'SBER', 'SBERP', 'SELG', 'SFIN', 'SGZH', 'SIBN', 'SLEN', 'SMLT', 'SNGS', 'SNGSP', 'SOFL', 'SPBE', 'STSB', 'STSBP', 'SVAV', 'SVCB', 'SVET', 'SVETP', 'TASB', 'TASBP', 'TATN', 'TATNP', 'TCSG', 'TGKA', 'TGKB', 'TGKBP', 'TGKN', 'TNSE', 'TORS', 'TORSP', 'TRMK', 'TRNFP', 'TTLK', 'TUZA', 'UGLD', 'UKUZ', 'UNAC', 'UNKL', 'UPRO', 'URKZ', 'USBN', 'UTAR', 'VEON-RX', 'VGSB', 'VGSBP', 'VJGZ', 'VJGZP', 'VKCO', 'VLHZ', 'VRSB', 'VRSBP', 'VSEH', 'VSMO', 'VSYD', 'VSYDP', 'VTBR', 'WTCM', 'WTCMP', 'WUSH', 'YAKG', 'YDEX', 'YKEN', 'YKENP', 'YRSB', 'YRSBP', 'ZAYM', 'ZILL', 'ZVEZ']

,begin,ABIO,ABRD,ACKO,AFKS,AFLT,AGRO,AKRN,ALRS,AMEZ,...,WUSH,YAKG,YDEX,YKEN,YKENP,YRSB,YRSBP,ZAYM,ZILL,ZVEZ
0,2022-07-01 09:00:00,57.78,NaN,NaN,14.310,26.60,859.6,18182,67.49,19.855,...,NaN,110.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2022-07-01 10:00:00,57.78,170.5,NaN,14.311,26.60,857.0,18022,67.47,20.055,...,NaN,110.00,NaN,0.2775,NaN,NaN,83.0,NaN,2940.0,3.545
2,2022-07-01 11:00:00,56.40,171.5,NaN,14.759,26.76,865.4,18358,66.29,19.825,...,NaN,104.25,NaN,NaN,NaN,172.0,82.5,NaN,2900.0,3.560
3,2022-07-01 12:00:00,56.38,170.0,NaN,14.798,27.44,858.8,18500,66.20,19.745,...,NaN,104.90,NaN,NaN,NaN,NaN,NaN,NaN,2915.0,NaN
4,2022-07-01 13:00:00,56.96,171.0,NaN,15.121,27.18,862.2,18578,66.42,19.750,...,NaN,106.10,NaN,NaN,NaN,NaN,NaN,NaN,2925.0,3.505

========================================================================================================================
RussianFinancialNews\candles_data\1h\value.csv
shape sample: (5, 253)
columns: ['begin', 'ABIO', 'ABRD', 'ACKO', 'AFKS', 'AFLT', 'AGRO', 'AKRN', 'ALRS', 'AMEZ', 'APRI', 'APTK', 'AQUA', 'ARSA', 'ASSB', 'ASTR', 'AVAN', 'BANE', 'BANEP', 'BELU', 'BISVP', 'BRZL', 'BSPB', 'BSPBP', 'CARM', 'CBOM', 'CHGZ', 'CHKZ', 'CHMF', 'CHMK', 'CIAN', 'CNTL', 'CNTLP', 'DELI', 'DIAS', 'DIOD', 'DVEC', 'DZRD', 'DZRDP', 'EELT', 'ELFV', 'ELMT', 'ENPG', 'ETLN', 'EUTR', 'FEES', 'FESH', 'FIVE', 'FIXP', 'FLOT', 'GAZC', 'GAZP', 'GAZS', 'GAZT', 'GCHE', 'GECO', 'GEMA', 'GEMC', 'GLTR', 'GMKN', 'HEAD', 'HHRU', 'HIMCP', 'HNFG', 'HYDR', 'IGST', 'IGSTP', 'INGR', 'IRAO', 'IRKT', 'IVAT', 'JNOS', 'JNOSP', 'KAZT', 'KAZTP', 'KBSB', 'KCHE', 'KCHEP', 'KGKC', 'KGKCP', 'KLSB', 'KLVZ', 'KMAZ', 'KMEZ', 'KOGK', 'KRKN', 'KRKNP', 'KRKOP', 'KROT', 'KROTP', 'KRSB', 'KRSBP', 'KUBE', 'KUZB', 'KZOS', 'KZOSP', 'LEAS', 'LENT', 'LKOH', 'LNZL', 'LNZLP', 'LSNG', 'LSNGP', 'LSRG', 'LVHK', 'MAGE', 'MAGEP', 'MAGN', 'MBNK', 'MDMG', 'MFGS', 'MFGSP', 'MGKL', 'MGNT', 'MGNZ', 'MGTS', 'MGTSP', 'MISB', 'MISBP', 'MOEX', 'MRKC', 'MRKK', 'MRKP', 'MRKS', 'MRKU', 'MRKV', 'MRKY', 'MRKZ', 'MRSB', 'MSNG', 'MSRS', 'MSTT', 'MTLR', 'MTLRP', 'MTSS', 'MVID', 'NAUK', 'NFAZ', 'NKHP', 'NKNC', 'NKNCP', 'NKSH', 'NLMK', 'NMTP', 'NNSB', 'NNSBP', 'NSVZ', 'NVTK', 'OGKB', 'OKEY', 'OMZZP', 'OZON', 'PHOR', 'PIKK', 'PLZL', 'PMSB', 'PMSBP', 'POLY', 'POSI', 'PRFN', 'PRMB', 'PRMD', 'QIWI', 'RASP', 'RDRB', 'RENI', 'RGSS', 'RKKE', 'RNFT', 'ROLO', 'ROSB', 'ROSN', 'ROST', 'RTGZ', 'RTKM', 'RTKMP', 'RTSB', 'RTSBP', 'RUAL', 'RUSI', 'RZSB', 'SAGO', 'SAGOP', 'SARE', 'SAREP', 'SBER', 'SBERP', 'SELG', 'SFIN', 'SGZH', 'SIBN', 'SLEN', 'SMLT', 'SNGS', 'SNGSP', 'SOFL', 'SPBE', 'STSB', 'STSBP', 'SVAV', 'SVCB', 'SVET', 'SVETP', 'TASB', 'TASBP', 'TATN', 'TATNP', 'TCSG', 'TGKA', 'TGKB', 'TGKBP', 'TGKN', 'TNSE', 'TORS', 'TORSP', 'TRMK', 'TRNFP', 'TTLK', 'TUZA', 'UGLD', 'UKUZ', 'UNAC', 'UNKL', 'UPRO', 'URKZ', 'USBN', 'UTAR', 'VEON-RX', 'VGSB', 'VGSBP', 'VJGZ', 'VJGZP', 'VKCO', 'VLHZ', 'VRSB', 'VRSBP', 'VSEH', 'VSMO', 'VSYD', 'VSYDP', 'VTBR', 'WTCM', 'WTCMP', 'WUSH', 'YAKG', 'YDEX', 'YKEN', 'YKENP', 'YRSB', 'YRSBP', 'ZAYM', 'ZILL', 'ZVEZ']

,begin,ABIO,ABRD,ACKO,AFKS,AFLT,AGRO,AKRN,ALRS,AMEZ,...,WUSH,YAKG,YDEX,YKEN,YKENP,YRSB,YRSBP,ZAYM,ZILL,ZVEZ
0,2022-07-01 09:00:00,6355.8,NaN,NaN,699759.0,329042.0,19770.8,90910,1867448.3,11913.0,...,NaN,154000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2022-07-01 10:00:00,2460292.8,375705.0,NaN,165283798.6,38754814.0,8855440.6,24445762,178916545.6,7506705.5,...,NaN,782428.5,NaN,2775.0,NaN,NaN,1660.0,NaN,532455.0,10655.0
2,2022-07-01 11:00:00,1162618.2,1049355.0,NaN,43834151.1,24851988.0,3107343.6,9992568,59456254.2,1192381.0,...,NaN,159484.0,NaN,NaN,NaN,1720.0,23805.0,NaN,141880.0,3560.0
3,2022-07-01 12:00:00,1444073.2,394545.0,NaN,183112423.7,24928228.8,4849090.6,13429390,156080792.3,1038661.0,...,NaN,287652.0,NaN,NaN,NaN,NaN,NaN,NaN,90365.0,NaN
4,2022-07-01 13:00:00,1641096.8,380475.0,NaN,67646197.2,7865622.6,1628007.2,8531568,53996465.4,907200.5,...,NaN,1130956.5,NaN,NaN,NaN,NaN,NaN,NaN,14640.0,17540.0

========================================================================================================================
RussianFinancialNews\candles_data\1h\volume.csv
shape sample: (5, 253)
columns: ['begin', 'ABIO', 'ABRD', 'ACKO', 'AFKS', 'AFLT', 'AGRO', 'AKRN', 'ALRS', 'AMEZ', 'APRI', 'APTK', 'AQUA', 'ARSA', 'ASSB', 'ASTR', 'AVAN', 'BANE', 'BANEP', 'BELU', 'BISVP', 'BRZL', 'BSPB', 'BSPBP', 'CARM', 'CBOM', 'CHGZ', 'CHKZ', 'CHMF', 'CHMK', 'CIAN', 'CNTL', 'CNTLP', 'DELI', 'DIAS', 'DIOD', 'DVEC', 'DZRD', 'DZRDP', 'EELT', 'ELFV', 'ELMT', 'ENPG', 'ETLN', 'EUTR', 'FEES', 'FESH', 'FIVE', 'FIXP', 'FLOT', 'GAZC', 'GAZP', 'GAZS', 'GAZT', 'GCHE', 'GECO', 'GEMA', 'GEMC', 'GLTR', 'GMKN', 'HEAD', 'HHRU', 'HIMCP', 'HNFG', 'HYDR', 'IGST', 'IGSTP', 'INGR', 'IRAO', 'IRKT', 'IVAT', 'JNOS', 'JNOSP', 'KAZT', 'KAZTP', 'KBSB', 'KCHE', 'KCHEP', 'KGKC', 'KGKCP', 'KLSB', 'KLVZ', 'KMAZ', 'KMEZ', 'KOGK', 'KRKN', 'KRKNP', 'KRKOP', 'KROT', 'KROTP', 'KRSB', 'KRSBP', 'KUBE', 'KUZB', 'KZOS', 'KZOSP', 'LEAS', 'LENT', 'LKOH', 'LNZL', 'LNZLP', 'LSNG', 'LSNGP', 'LSRG', 'LVHK', 'MAGE', 'MAGEP', 'MAGN', 'MBNK', 'MDMG', 'MFGS', 'MFGSP', 'MGKL', 'MGNT', 'MGNZ', 'MGTS', 'MGTSP', 'MISB', 'MISBP', 'MOEX', 'MRKC', 'MRKK', 'MRKP', 'MRKS', 'MRKU', 'MRKV', 'MRKY', 'MRKZ', 'MRSB', 'MSNG', 'MSRS', 'MSTT', 'MTLR', 'MTLRP', 'MTSS', 'MVID', 'NAUK', 'NFAZ', 'NKHP', 'NKNC', 'NKNCP', 'NKSH', 'NLMK', 'NMTP', 'NNSB', 'NNSBP', 'NSVZ', 'NVTK', 'OGKB', 'OKEY', 'OMZZP', 'OZON', 'PHOR', 'PIKK', 'PLZL', 'PMSB', 'PMSBP', 'POLY', 'POSI', 'PRFN', 'PRMB', 'PRMD', 'QIWI', 'RASP', 'RDRB', 'RENI', 'RGSS', 'RKKE', 'RNFT', 'ROLO', 'ROSB', 'ROSN', 'ROST', 'RTGZ', 'RTKM', 'RTKMP', 'RTSB', 'RTSBP', 'RUAL', 'RUSI', 'RZSB', 'SAGO', 'SAGOP', 'SARE', 'SAREP', 'SBER', 'SBERP', 'SELG', 'SFIN', 'SGZH', 'SIBN', 'SLEN', 'SMLT', 'SNGS', 'SNGSP', 'SOFL', 'SPBE', 'STSB', 'STSBP', 'SVAV', 'SVCB', 'SVET', 'SVETP', 'TASB', 'TASBP', 'TATN', 'TATNP', 'TCSG', 'TGKA', 'TGKB', 'TGKBP', 'TGKN', 'TNSE', 'TORS', 'TORSP', 'TRMK', 'TRNFP', 'TTLK', 'TUZA', 'UGLD', 'UKUZ', 'UNAC', 'UNKL', 'UPRO', 'URKZ', 'USBN', 'UTAR', 'VEON-RX', 'VGSB', 'VGSBP', 'VJGZ', 'VJGZP', 'VKCO', 'VLHZ', 'VRSB', 'VRSBP', 'VSEH', 'VSMO', 'VSYD', 'VSYDP', 'VTBR', 'WTCM', 'WTCMP', 'WUSH', 'YAKG', 'YDEX', 'YKEN', 'YKENP', 'YRSB', 'YRSBP', 'ZAYM', 'ZILL', 'ZVEZ']

,begin,ABIO,ABRD,ACKO,AFKS,AFLT,AGRO,AKRN,ALRS,AMEZ,...,WUSH,YAKG,YDEX,YKEN,YKENP,YRSB,YRSBP,ZAYM,ZILL,ZVEZ
0,2022-07-01 09:00:00,110,NaN,NaN,48900,12370,23,5,27670,600,...,NaN,1400,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2022-07-01 10:00:00,43610,2190.0,NaN,11302000,1457100,10268,1328,2703470,369900,...,NaN,7270,NaN,10000.0,NaN,NaN,20.0,NaN,183.0,3000.0
2,2022-07-01 11:00:00,20650,6170.0,NaN,2962000,917430,3608,543,898490,60400,...,NaN,1530,NaN,NaN,NaN,10.0,290.0,NaN,49.0,1000.0
3,2022-07-01 12:00:00,25440,2310.0,NaN,12139400,912170,5636,722,2355850,52600,...,NaN,2730,NaN,NaN,NaN,NaN,NaN,NaN,31.0,NaN
4,2022-07-01 13:00:00,29160,2230.0,NaN,4466400,290080,1891,459,815700,45700,...,NaN,10770,NaN,NaN,NaN,NaN,NaN,NaN,5.0,5000.0

========================================================================================================================
RussianFinancialNews\preview.csv
shape sample: (5, 7)
columns: ['Unnamed: 0', 'title', 'body', 'date', 'time', 'tags', 'source']

,Unnamed: 0,title,body,date,time,tags,source
0,5487,no title,""" Государство может «подарить» деньги Сегеже (...",2022-06-14,11:51:00,[],rdv
1,43765,Mail.ru Group сообщила о росте выручки на 17% ...,Компания опубликовала финансовые результаты за...,2021-07-29 00:00:00,not stated,['ВК (ранее VK) VKCO'],bcs
2,36447,Автопарк каршеринг-сервиса Делимобиль в I полу...,В июле количество авто уже превысило 30 тысяч,2024-07-25 00:00:00,11:17,['Каршеринг (Делимобиль) DELI'],bcs
3,45110,Мнения аналитиков. Об отчетности ВТБ и стратег...,Эти и другие события дня комментируют эксперты...,2020-08-04 00:00:00,not stated,[],bcs
4,45825,Ожидаемые события на 14 июня,"Банк России проведет заседание, выйдут данные ...",2019-06-14 00:00:00,not stated,[],bcs

In [4]:
from pathlib import Path
import pandas as pd
import json

DATA_DIR = Path("../data/external/kaggle/russian_financial_news/RussianFinancialNews")

news_path = DATA_DIR / "news_collection.parquet"
news_old_path = DATA_DIR / "news_descriptions" / "news_collection_old.parquet"
tickers_path = DATA_DIR / "tickers_description.json"
gpt4o_path = DATA_DIR / "news_descriptions" / "news_descriptions_GPT4o.json"
llama_path = DATA_DIR / "news_descriptions" / "news_description_Llama3_8b.json"

In [5]:
news = pd.read_parquet(news_path)

print(news.shape)
print(news.columns.tolist())

display(news.head())
display(news.sample(5, random_state=42))

(91955, 6)
['title', 'body', 'date', 'time', 'tags', 'source']

,title,body,date,time,tags,source
0,no title,"""После падения добычи в 2022-2023 годах Газпро...",2024-09-09,16:16:54,['цифры'],rdv
1,no title,""" Рейтинг акций комьюнити РДВ. #опрос """,2024-09-09,15:38:21,['опрос'],rdv
2,no title,"""Нефть Brent упала до $71, Urals - до $60 за б...",2024-09-09,14:40:17,['шокновости'],rdv
3,no title,"""️ Ставка ЦБ вряд ли уйдёт выше 18%. ЦБ переже...",2024-09-09,12:54:10,['VIPtalk'],rdv
4,no title,"""Эксперты клуба RDV PREMIUM 361° дали коммента...",2024-09-09,10:25:07,[],rdv

,title,body,date,time,tags,source
48867,Транснефть-ап. Ближайшая цель роста – 1600,Вчера привилегированные акции Транснефти подор...,2024-06-27 00:00:00,not stated,Транснефть ап,bcs_tech
77263,no title,Индия сократила импорт нефти из России в октяб...,2023-11-01,not stated,no tags,smart_lab
57915,no title,Танкерные перевозки российской нефти выросли в...,2022-05-04,not stated,no tags,smart_lab
78101,no title,Представители Главного таможенного управления ...,2023-11-24,not stated,no tags,smart_lab
21692,"Выручка ""Ростелекома"" в 2022 году составила 65...",По итогам 2021 года выручка компании по МСФО с...,2023-02-06,not stated,['Ростел ао'],finam

In [6]:
for col in news.columns:
    print("\n" + "=" * 80)
    print(col)
    print(news[col].head(10).to_string())

================================================================================
title
0     no title
1     no title
2     no title
3     no title
4     no title
6     no title
7     no title
8     no title
9     no title
13    no title

================================================================================
body
0     "После падения добычи в 2022-2023 годах Газпро...
1             " Рейтинг акций комьюнити РДВ. #опрос   "
2     "Нефть Brent упала до $71, Urals - до $60 за б...
3     "️ Ставка ЦБ вряд ли уйдёт выше 18%. ЦБ переже...
4     "Эксперты клуба RDV PREMIUM 361° дали коммента...
6     "Эксперты клуба RDV PREMIUM 361° дали коммента...
7     "Выручка девелоперов в Московском регионе (Мос...
8     "Рейтинг акций коммьюнити РДВ. #опрос Какой ак...
9     " Рейтинг дивдоходностей за 2024 год. Прогноз ...
13    "Главное к открытию понедельника (09.09): #бри...

================================================================================
date
0     2024-09-09
1     2024-09-09
2     2024-09-09
3     2024-09-09
4     2024-09-09
6     2024-09-09
7     2024-09-09
8     2024-09-09
9     2024-09-09
13    2024-09-09

================================================================================
time
0     16:16:54
1     15:38:21
2     14:40:17
3     12:54:10
4     10:25:07
6     10:25:06
7     09:11:47
8     08:56:44
9     07:51:20
13    06:26:47

================================================================================
tags
0          ['цифры']
1          ['опрос']
2     ['шокновости']
3        ['VIPtalk']
4                 []
6                 []
7      ['аналитика']
8          ['опрос']
9          ['цифры']
13       ['брифинг']

================================================================================
source
0     rdv
1     rdv
2     rdv
3     rdv
4     rdv
6     rdv
7     rdv
8     rdv
9     rdv
13    rdv

In [7]:
date_like_cols = [
    col for col in news.columns
    if any(word in col.lower() for word in ["date", "time", "publish", "created"])
]

date_like_cols

['date', 'time']

In [8]:
for col in date_like_cols:
    print("\n", col)
    print(news[col].head(10))
    print(news[col].min(), news[col].max())

 date
0     2024-09-09
1     2024-09-09
2     2024-09-09
3     2024-09-09
4     2024-09-09
6     2024-09-09
7     2024-09-09
8     2024-09-09
9     2024-09-09
13    2024-09-09
Name: date, dtype: str
2009-06-19 00:00:00 2024-12-16 00:00:00

 time
0     16:16:54
1     15:38:21
2     14:40:17
3     12:54:10
4     10:25:07
6     10:25:06
7     09:11:47
8     08:56:44
9     07:51:20
13    06:26:47
Name: time, dtype: str
00:00 not stated

In [9]:
text_like_cols = [
    col for col in news.columns
    if any(word in col.lower() for word in ["title", "text", "body", "content", "news", "description"])
]

text_like_cols

['title', 'body']

In [10]:
for col in text_like_cols:
    print("\n" + "=" * 100)
    print(col)
    print(news[col].dropna().astype(str).head(3).to_string())

====================================================================================================
title
0    no title
1    no title
2    no title

====================================================================================================
body
0    "После падения добычи в 2022-2023 годах Газпро...
1            " Рейтинг акций комьюнити РДВ. #опрос   "
2    "Нефть Brent упала до $71, Urals - до $60 за б...

In [11]:
ticker_like_cols = [
    col for col in news.columns
    if any(word in col.lower() for word in ["ticker", "secid", "company", "issuer", "symbol"])
]

ticker_like_cols

[]

In [12]:
for col in ticker_like_cols:
    print("\n" + "=" * 100)
    print(col)
    print(news[col].dropna().astype(str).head(20).to_string())
    print("unique:", news[col].nunique())

In [13]:
with open(tickers_path, "r", encoding="utf-8") as f:
    tickers_description = json.load(f)

type(tickers_description)

dict

In [14]:
if isinstance(tickers_description, list):
    tickers_df = pd.DataFrame(tickers_description)
else:
    tickers_df = pd.DataFrame.from_dict(tickers_description, orient="index").reset_index()

print(tickers_df.shape)
print(tickers_df.columns.tolist())
display(tickers_df.head(20))

(238, 2)
['index', 0]

    index                                                  0
0    ABIO  Артген биотех (ранее Институт Стволовых Клеток...
1    ABRD  Завод шампанских вин «Абрау-Дюрсо» — крупнейши...
2    AFKS  АФК «Система» является одной из самых крупных ...
3    AFLT  ПАО «Аэрофлот» — крупнейший авиаперевозчик Рос...
4    AKRN  ПАО «Акрон» — один из ведущих вертикально инте...
5    ALRS  ПАО «АЛРОСА» — лидер алмазодобывающей отрасли ...
6    APRI  Специализируясь на реализации проектов строите...
7    APTK  ПАО «Аптечная сеть 36,6» — крупная российская ...
8    AQUA  ПАО «ИНАРКТИКА» (ранее Русская Аквакультура) я...
9    ARSA  ПАО «Управляющая компания «Арсагера» — первая ...
10   ASSB  ПАО "Астраханская энергосбытовая компания" осу...
11   ASTR  Группа компаний «Астра» — один из лидеров росс...
12   AVAN  ПАО АКБ «АВАНГАРД» - основан в 1994 году. Унив...
13   BANE  ПАО АНК Башнефть — российская вертикально—инте...
14  BANEP  ПАО АНК Башнефть — российская вертикально—инте...
15   BELU  ПАО «НоваБев Групп» — Novabev Group (ранее Бел...
16  BISVP  ПАО "Башинформсвязь" — один из крупнейших опер...
17   BLNG  ОАО «Белон» — создано в Новосибирске в мае 199...
18   BRZL  ОАО Бурятзолото — крупная золотодобывающая ком...
19   BSPB  ПАО Банк Санкт-Петербург — один из крупнейших ...

In [15]:
with open(gpt4o_path, "r", encoding="utf-8") as f:
    gpt4o_data = json.load(f)

type(gpt4o_data)

dict

In [16]:
if isinstance(gpt4o_data, list):
    print("list length:", len(gpt4o_data))
    print(gpt4o_data[0])
elif isinstance(gpt4o_data, dict):
    print("dict length:", len(gpt4o_data))
    first_key = next(iter(gpt4o_data))
    print("first key:", first_key)
    print(gpt4o_data[first_key])

dict length: 15000
first key: 0
{'thinking': "The article discusses Gazprom's production figures, highlighting a discrepancy between gas and oil revenue, and mentioning potential market changes in Russia's energy strategy. This is a financial report as it concerns company performance metrics (revenue figures) and an upcoming policy decision that could affect the gas market.", 'article_type': 'finance', 'country': ['Russia'], 'sectors': ['Energy'], 'tickers': ['GAZP'], 'sentiment_score': -0.5}

In [17]:
with open(llama_path, "r", encoding="utf-8") as f:
    llama_data = json.load(f)

if isinstance(llama_data, list):
    print("list length:", len(llama_data))
    print(llama_data[0])
elif isinstance(llama_data, dict):
    print("dict length:", len(llama_data))
    first_key = next(iter(llama_data))
    print("first key:", first_key)
    print(llama_data[first_key])

dict length: 24398
first key: 0
{'thinking': "The article discusses the recent trend in Gazprom's oil and gas production, highlighting that despite a significant increase in natural gas extraction, the revenue from gas sales has decreased compared to oil sales. This could potentially impact Russia's energy market and the country's overall economy.", 'description': {'article_type': 'finance', 'country': ['Russia'], 'sectors': ['Energy'], 'tickers': ['GAZP'], 'sentiment_score': -0.5}}

In [18]:
print(news.shape)
print(news.columns.tolist())
display(news.head())

(91955, 6)
['title', 'body', 'date', 'time', 'tags', 'source']

,title,body,date,time,tags,source
0,no title,"""После падения добычи в 2022-2023 годах Газпро...",2024-09-09,16:16:54,['цифры'],rdv
1,no title,""" Рейтинг акций комьюнити РДВ. #опрос """,2024-09-09,15:38:21,['опрос'],rdv
2,no title,"""Нефть Brent упала до $71, Urals - до $60 за б...",2024-09-09,14:40:17,['шокновости'],rdv
3,no title,"""️ Ставка ЦБ вряд ли уйдёт выше 18%. ЦБ переже...",2024-09-09,12:54:10,['VIPtalk'],rdv
4,no title,"""Эксперты клуба RDV PREMIUM 361° дали коммента...",2024-09-09,10:25:07,[],rdv

In [19]:
display(tickers_df.head(20))

    index                                                  0
0    ABIO  Артген биотех (ранее Институт Стволовых Клеток...
1    ABRD  Завод шампанских вин «Абрау-Дюрсо» — крупнейши...
2    AFKS  АФК «Система» является одной из самых крупных ...
3    AFLT  ПАО «Аэрофлот» — крупнейший авиаперевозчик Рос...
4    AKRN  ПАО «Акрон» — один из ведущих вертикально инте...
5    ALRS  ПАО «АЛРОСА» — лидер алмазодобывающей отрасли ...
6    APRI  Специализируясь на реализации проектов строите...
7    APTK  ПАО «Аптечная сеть 36,6» — крупная российская ...
8    AQUA  ПАО «ИНАРКТИКА» (ранее Русская Аквакультура) я...
9    ARSA  ПАО «Управляющая компания «Арсагера» — первая ...
10   ASSB  ПАО "Астраханская энергосбытовая компания" осу...
11   ASTR  Группа компаний «Астра» — один из лидеров росс...
12   AVAN  ПАО АКБ «АВАНГАРД» - основан в 1994 году. Унив...
13   BANE  ПАО АНК Башнефть — российская вертикально—инте...
14  BANEP  ПАО АНК Башнефть — российская вертикально—инте...
15   BELU  ПАО «НоваБев Групп» — Novabev Group (ранее Бел...
16  BISVP  ПАО "Башинформсвязь" — один из крупнейших опер...
17   BLNG  ОАО «Белон» — создано в Новосибирске в мае 199...
18   BRZL  ОАО Бурятзолото — крупная золотодобывающая ком...
19   BSPB  ПАО Банк Санкт-Петербург — один из крупнейших ...

In [20]:
news["published_at"] = pd.to_datetime(
    news["date"].astype(str) + " " + news["time"].astype(str),
    errors="coerce"
)

print(news["published_at"].min())
print(news["published_at"].max())
print(news["published_at"].isna().mean())

print(news["body"].isna().mean())
print(news["body"].astype(str).str.len().describe())

display(news[["body", "published_at", "tags", "source"]].sample(10, random_state=42))

2022-05-26 13:32:40
2024-12-15 13:41:06
0.8801478984285792
0.0
count    91955.000000
mean       601.574770
std       1231.309845
min          7.000000
25%         71.000000
50%        101.000000
75%        186.000000
max       5849.000000
Name: body, dtype: float64

,body,published_at,tags,source
48867,Вчера привилегированные акции Транснефти подор...,NaT,Транснефть ап,bcs_tech
77263,Индия сократила импорт нефти из России в октяб...,NaT,no tags,smart_lab
57915,Танкерные перевозки российской нефти выросли в...,NaT,no tags,smart_lab
78101,Представители Главного таможенного управления ...,NaT,no tags,smart_lab
21692,По итогам 2021 года выручка компании по МСФО с...,NaT,['Ростел ао'],finam
32804,"На первый план вышли другие факторы, такие как...",NaT,"['Ростел ао', 'ЛУКОЙЛ', 'Мвидео', 'Татнфт ао',...",finam
85305,В новый санкционный список США попала страхова...,NaT,no tags,smart_lab
39142,Росстат опубликовал данные по динамике потреби...,NaT,[],bcs
15123,Увеличивается возраст заемщика на момент выпла...,NaT,[],finam
29701,Центр создан на базе Института математики и ко...,NaT,"['Сбербанк', 'Сбербанкп']",finam

In [21]:
from pathlib import Path
import pandas as pd

DATA_DIR = Path("../data/external/kaggle/russian_financial_news/RussianFinancialNews")

close_1h = pd.read_csv(DATA_DIR / "candles_data" / "1h" / "close.csv")

print(close_1h.shape)
print(close_1h.columns[:20].tolist())
print(close_1h.columns[-20:].tolist())

(8039, 253)
['begin', 'ABIO', 'ABRD', 'ACKO', 'AFKS', 'AFLT', 'AGRO', 'AKRN', 'ALRS', 'AMEZ', 'APRI', 'APTK', 'AQUA', 'ARSA', 'ASSB', 'ASTR', 'AVAN', 'BANE', 'BANEP', 'BELU']
['VLHZ', 'VRSB', 'VRSBP', 'VSEH', 'VSMO', 'VSYD', 'VSYDP', 'VTBR', 'WTCM', 'WTCMP', 'WUSH', 'YAKG', 'YDEX', 'YKEN', 'YKENP', 'YRSB', 'YRSBP', 'ZAYM', 'ZILL', 'ZVEZ']

In [22]:
SELECTED_TICKERS = [
    "SBER",
    "GAZP",
    "ROSN",
    "NVTK",
    "GMKN",
    "PLZL",
    "TATN",
    "AFLT",
    "YDEX",
    "VKCO",
]

available = [ticker for ticker in SELECTED_TICKERS if ticker in close_1h.columns]
missing = [ticker for ticker in SELECTED_TICKERS if ticker not in close_1h.columns]

print("available:", available)
print("missing:", missing)

available: ['SBER', 'GAZP', 'ROSN', 'NVTK', 'GMKN', 'PLZL', 'TATN', 'AFLT', 'YDEX', 'VKCO']
missing: []

In [24]:
df_final = pd.read_parquet('../data/raw/market/df_final.parquet')

In [31]:
market = df_selected.copy()

market["begin"] = pd.to_datetime(market["begin"])
news["published_at"] = pd.to_datetime(
    news["date"].astype(str).str.strip() + " " + news["time"].astype(str).str.strip(),
    errors="coerce"
)

market_start = market["begin"].min()
market_end = market["begin"].max()

news_start = news["published_at"].min()
news_end = news["published_at"].max()

overlap_start = max(market_start, news_start)
overlap_end = min(market_end, news_end)

print("market:", market_start, "→", market_end)
print("news:", news_start, "→", news_end)
print("overlap:", overlap_start, "→", overlap_end)

market: 2024-01-03 09:00:00 → 2025-12-09 16:00:00
news: 2022-05-26 13:32:40 → 2024-12-15 13:41:06
overlap: 2024-01-03 09:00:00 → 2024-12-15 13:41:06

In [32]:
news_2024 = news[
    (news["published_at"] >= overlap_start) &
    (news["published_at"] <= overlap_end)
].copy()

print(news_2024.shape)
print(news_2024["published_at"].min(), news_2024["published_at"].max())

(4168, 7)
2024-01-03 09:08:20 2024-12-15 13:41:06

In [33]:
market_2024 = market[
    (market["begin"] >= overlap_start) &
    (market["begin"] <= overlap_end)
].copy()

print(market_2024.shape)
print(market_2024["begin"].min(), market_2024["begin"].max())

(34384, 9)
2024-01-03 09:00:00 2024-12-13 23:00:00

In [28]:
SELECTED_TICKERS = [
    "SBER",
    "GAZP",
    "ROSN",
    "NVTK",
    "GMKN",
    "PLZL",
    "TATN",
    "AFLT",
    "YDEX",
    "VKCO",
]

In [29]:
df_selected = df_final[df_final["ticker"].isin(SELECTED_TICKERS)].copy()

In [30]:
df_selected

,begin,ticker,open,close,high,low,value,volume,end
11888,2024-01-03 09:00:00,AFLT,35.22,35.22,35.22,35.22,461734.2,13110.0,2024-01-03 09:59:59
11889,2024-01-03 10:00:00,AFLT,35.21,35.66,35.67,35.12,41835092.0,1180530.0,2024-01-03 10:59:59
11890,2024-01-03 11:00:00,AFLT,35.67,35.48,35.68,35.40,30396905.1,855550.0,2024-01-03 11:59:59
11891,2024-01-03 12:00:00,AFLT,35.48,35.55,35.55,35.36,10632512.4,299980.0,2024-01-03 12:59:59
11892,2024-01-03 13:00:00,AFLT,35.53,35.59,35.62,35.44,14603209.0,410780.0,2024-01-03 13:59:59
...,...,...,...,...,...,...,...,...,...
77256,2025-12-09 12:00:00,YDEX,4321.00,4325.50,4329.00,4314.50,98582315.5,22808.0,2025-12-09 12:59:59
77257,2025-12-09 13:00:00,YDEX,4325.50,4316.50,4334.50,4315.50,120564264.5,27876.0,2025-12-09 13:59:59
77258,2025-12-09 14:00:00,YDEX,4316.50,4330.00,4340.50,4315.00,281067170.5,64909.0,2025-12-09 14:59:59
77259,2025-12-09 15:00:00,YDEX,4331.00,4325.00,4334.00,4318.50,147005619.5,33977.0,2025-12-09 15:59:59
77260,2025-12-09 16:00:00,YDEX,4325.00,4318.00,4331.50,4318.00,30838394.5,7130.0,2025-12-09 16:29:42

In [34]:
project_start = market_2024["begin"].min()
project_end = market_2024["begin"].max()

print(project_start, "→", project_end)

2024-01-03 09:00:00 → 2024-12-13 23:00:00

In [35]:
news_project = news[
    (news["published_at"] >= project_start) &
    (news["published_at"] <= project_end)
].copy()

market_project = market[
    (market["begin"] >= project_start) &
    (market["begin"] <= project_end)
].copy()

print("news_project:", news_project.shape)
print(news_project["published_at"].min(), news_project["published_at"].max())

print("market_project:", market_project.shape)
print(market_project["begin"].min(), market_project["begin"].max())

news_project: (4161, 7)
2024-01-03 09:08:20 2024-12-13 16:37:38
market_project: (34384, 9)
2024-01-03 09:00:00 2024-12-13 23:00:00

In [36]:
market_time_grid = (
    market_project[["begin", "ticker"]]
    .drop_duplicates()
    .rename(columns={"begin": "datetime"})
    .sort_values(["ticker", "datetime"])
    .reset_index(drop=True)
)

market_time_grid.head()

             datetime ticker
0 2024-01-03 09:00:00   AFLT
1 2024-01-03 10:00:00   AFLT
2 2024-01-03 11:00:00   AFLT
3 2024-01-03 12:00:00   AFLT
4 2024-01-03 13:00:00   AFLT

In [37]:
market_time_grid

                 datetime ticker
0     2024-01-03 09:00:00   AFLT
1     2024-01-03 10:00:00   AFLT
2     2024-01-03 11:00:00   AFLT
3     2024-01-03 12:00:00   AFLT
4     2024-01-03 13:00:00   AFLT
...                   ...    ...
34379 2024-12-13 19:00:00   YDEX
34380 2024-12-13 20:00:00   YDEX
34381 2024-12-13 21:00:00   YDEX
34382 2024-12-13 22:00:00   YDEX
34383 2024-12-13 23:00:00   YDEX

[34384 rows x 2 columns]

In [38]:
from pathlib import Path
import pandas as pd

news_path = Path("../data/interim/news/kaggle_news_canonical_2024.parquet")

news_canonical = pd.read_parquet(news_path)

print(news_canonical.shape)
print(news_canonical["published_at"].min())
print(news_canonical["published_at"].max())
display(news_canonical.head())
display(news_canonical.sample(5, random_state=42))

(4161, 10)
2024-01-03 09:08:20
2024-12-13 16:37:38

,news_id,raw_news_id,published_at,date,time,title,text,tags,source,raw_source
0,kaggle_rfn_1605,1605,2024-01-03 09:08:20,2024-01-03,09:08:20,NaN,"""ЕС ВВЕЛ САНКЦИИ ПРОТИВ РОССИЙСКОЙ КОМПАНИИ ""А...",[],rdv,kaggle_russian_financial_news
1,kaggle_rfn_7989,7989,2024-01-03 11:48:00,2024-01-03,11:48:00,NaN,"""​​Меняем вещи на акции: теперь и в популярных...",[],t_invest,kaggle_russian_financial_news
2,kaggle_rfn_1604,1604,2024-01-04 06:29:24,2024-01-04,06:29:24,NaN,"""Главное к открытию четверга (04.01): #брифинг...",['брифинг'],rdv,kaggle_russian_financial_news
3,kaggle_rfn_1603,1603,2024-01-04 07:13:22,2024-01-04,07:13:22,NaN,"""️ Источники РДВ выбирают на 2024 год бумаги Ц...",['аналитика'],rdv,kaggle_russian_financial_news
4,kaggle_rfn_1602,1602,2024-01-04 07:19:21,2024-01-04,07:19:21,NaN,""" Циан (CIAN): справедливая цена акций 1027 ру...",['оценка'],rdv,kaggle_russian_financial_news

,news_id,raw_news_id,published_at,date,time,title,text,tags,source,raw_source
3540,kaggle_rfn_10689,10689,2024-10-26 09:21:53,2024-10-26,09:21:53,NaN,"""Президентские выборы в США: что они значат дл...","['макро', 'сша']",t_analytic,kaggle_russian_financial_news
3176,kaggle_rfn_6589,6589,2024-09-27 08:55:25,2024-09-27,08:55:25,NaN,"""Из грязи в князи: рецепт успеха миллионера из...",[],t_invest,kaggle_russian_financial_news
175,kaggle_rfn_1491,1491,2024-01-22 14:41:35,2024-01-22,14:41:35,NaN,"""️ Дисконт между китайскими акциями в Гонконге...","['РЦБвмире', 'Китай']",rdv,kaggle_russian_financial_news
3054,kaggle_rfn_6042,6042,2024-09-17 11:14:17,2024-09-17,11:14:17,NaN,""" Что нужно знать инвестору при выборе криптоб...",['РДВобразовательный'],rdv,kaggle_russian_financial_news
2112,kaggle_rfn_10787,10787,2024-07-04 08:40:30,2024-07-04,08:40:30,NaN,"""​​Инфляция ускоряется — ждем повышения ключев...","['россия', 'макро']",t_analytic,kaggle_russian_financial_news

In [42]:
from pathlib import Path
import pandas as pd

news_path = Path("../data/interim/news/kaggle_news_canonical_2024.parquet")
links_path = Path("../data/interim/news/news_ticker_links_2024.parquet")

news = pd.read_parquet(news_path)
links = pd.read_parquet(links_path)

print("news:", news.shape)
print("links:", links.shape)

print(links["ticker"].value_counts().sort_index())
print(links["match_type"].value_counts())

display(links.head())

news: (4161, 10)
links: (1060, 4)
ticker
AFLT     65
GAZP    173
GMKN     74
NVTK    106
PLZL     65
ROSN     82
SBER    180
TATN     63
VKCO      6
YDEX    246
Name: count, dtype: int64
match_type
text    1053
tag        7
Name: count, dtype: int64

            news_id ticker match_type matched_alias
0  kaggle_rfn_10687   AFLT       text      аэрофлот
1  kaggle_rfn_10758   AFLT       text      аэрофлот
2  kaggle_rfn_10803   AFLT       text      аэрофлот
3  kaggle_rfn_10833   AFLT       text      аэрофлот
4  kaggle_rfn_10896   AFLT       text      аэрофлот

In [43]:
linked_news = links.merge(news, on="news_id", how="left")

display(
    linked_news[
        ["ticker", "match_type", "matched_alias", "published_at", "text", "tags", "source"]
    ].sample(20, random_state=42)
)

,ticker,match_type,matched_alias,published_at,text,tags,source
972,YDEX,text,yandex,2024-08-23 12:53:00,"""​​«Подумал, что это какое-то отложенное посту...",[],t_invest
312,NVTK,text,новатэк,2024-04-04 11:03:01,"""#NVTK Новатэк думает сократить число линий сж...",['NVTK'],rdv
70,GAZP,text,газпром,2024-06-17 11:17:58,"""Ключевые события прошлой недели — в нашем дай...",['дайджест'],t_analytic
1028,YDEX,text,яндекс,2024-02-26 06:44:00,"""США и Евросоюз ввели новые санкции в отношени...",['новости'],t_invest
1021,YDEX,text,yandex,2024-03-15 14:46:03,"""Подводим итоги недели традиционным дайджестом...",[],t_invest
716,SBER,text,сбербанк,2024-03-12 06:42:35,"""Россия начала экспорт нефти в Венесуэлу На чт...",['новости'],t_invest
308,GMKN,text,норникель,2024-01-29 06:43:00,"""Строительство «Силы Сибири — 2» может быть от...",['новости'],t_invest
661,SBER,text,сбер,2024-10-12 13:35:35,"""О чем говорят инвесторы: дивиденды ТКС, потен...","['SBER', 'TCSG', 'VTBR', 'LKOH', 'TATN']",t_invest
174,GAZP,text,газпром,2024-08-16 13:23:31,"""О чем говорят инвесторы: ракета AMEZ, дивиден...","['EUTR', 'AMEZ', 'SBER', 'YDEX', 'GAZP']",t_invest
192,GAZP,text,газпром,2024-06-26 06:39:42,"""Чистая прибыль банковского сектора РФ в мае с...",['новости'],t_invest
352,NVTK,text,новатэк,2024-09-26 10:17:55,"""️Справедливая цена акций Новатэк (NVTK) 950 р...",['оценка'],rdv
428,PLZL,text,полюс,2024-03-28 08:09:40,""" Почему олигархи покупают золото? Нужно ли зо...",['VIPtalk'],rdv
109,GAZP,text,газпром,2024-09-03 13:48:35,""" Газпром (GAZP) — теперь, в основном, нефтяна...",['цифры'],rdv
1003,YDEX,text,яндекс,2024-05-14 12:37:17,"""Рокировка ценными бумагами Яндекса на Мосбирж...",['новости'],t_invest
290,GMKN,text,норникель,2024-05-22 06:41:01,"""Инвестиции в российские IT-технологии превыси...",['новости'],t_invest
96,GAZP,text,газпром,2024-01-26 08:51:16,""" Мультипликатор EV/EBITDA* российских нефтяны...",['цифры'],rdv
538,ROSN,text,роснефть,2024-05-23 06:41:38,"""Инфляция в России ускорилась до 8,1% в годово...",['новости'],t_invest
950,YDEX,text,яндекс,2024-10-09 14:55:10,"""​​ Разыгрываем автомобиль среди участников То...",[],t_invest
178,GAZP,text,газпром,2024-07-26 06:37:51,"""Курс юаня обновил минимум с начала месяца На ...",['новости'],t_invest
888,YDEX,text,яндекс,2024-07-31 13:35:22,"""Навес продаж после реструктуризации создал во...",['аналитика'],rdv

In [44]:
from pathlib import Path
import pandas as pd

news_for_llm_path = Path("../data/interim/news/news_for_llm_2024.parquet")

news_for_llm = pd.read_parquet(news_for_llm_path)

print(news_for_llm.shape)
print(news_for_llm["published_at"].min())
print(news_for_llm["published_at"].max())

print(news_for_llm["ticker"].value_counts().sort_index())

display(news_for_llm.head())
display(news_for_llm.sample(20, random_state=42))

(1060, 11)
2024-01-04 11:48:00
2024-12-13 16:37:38
ticker
AFLT     65
GAZP    173
GMKN     74
NVTK    106
PLZL     65
ROSN     82
SBER    180
TATN     63
VKCO      6
YDEX    246
Name: count, dtype: int64

,news_id,ticker,published_at,title,text,text_length,tags,source,raw_source,match_type,matched_alias
0,kaggle_rfn_7987,AFLT,2024-01-04 11:48:00,NaN,"""​​Жадный инвестор: лучшие выпуски 2023 года В...",2185,[],t_invest,kaggle_russian_financial_news,text,аэрофлот
1,kaggle_rfn_1464,AFLT,2024-01-26 09:53:54,NaN,""" Национальный интерес в цифровом суверенитете...",1128,['заработкинаСВО'],rdv,kaggle_russian_financial_news,text,аэрофлот
2,kaggle_rfn_1359,AFLT,2024-02-09 06:30:01,NaN,"""Главное к открытию пятницы (9.02): #брифинг З...",757,['брифинг'],rdv,kaggle_russian_financial_news,text,аэрофлот
3,kaggle_rfn_7822,AFLT,2024-02-09 06:50:00,NaN,"""Россия готова начать поставки газа в Европу п...",3147,['новости'],t_invest,kaggle_russian_financial_news,text,аэрофлот
4,kaggle_rfn_7813,AFLT,2024-02-09 16:14:00,NaN,""" Как закрылась основная торговая сессия на ро...",304,[],t_invest,kaggle_russian_financial_news,text,аэрофлот

,news_id,ticker,published_at,title,text,text_length,tags,source,raw_source,match_type,matched_alias
972,kaggle_rfn_322,YDEX,2024-07-25 12:04:44,NaN,""" Самолет Плюс сейчас — это Яндекс.Такси или U...",463,['VIPtalk'],rdv,kaggle_russian_financial_news,text,яндекс
312,kaggle_rfn_7982,NVTK,2024-01-09 06:45:00,NaN,"""Российские банки выходят на рынок Индии, а ЦБ...",2388,['новости'],t_invest,kaggle_russian_financial_news,text,новатэк
70,kaggle_rfn_7897,GAZP,2024-01-29 06:43:00,NaN,"""Строительство «Силы Сибири — 2» может быть от...",3037,['новости'],t_invest,kaggle_russian_financial_news,text,газпром
1028,kaggle_rfn_6556,YDEX,2024-10-03 15:45:00,NaN,"""​​Какие акции стоит купить прямо сейчас? Онла...",569,[],t_invest,kaggle_russian_financial_news,text,яндекс
1021,kaggle_rfn_10728,YDEX,2024-09-21 08:24:32,NaN,"""Металлурги и дивиденды В эфире подкаст Жадный...",429,[],t_analytic,kaggle_russian_financial_news,text,яндекс
716,kaggle_rfn_5754,SBER,2024-10-31 06:34:29,NaN,"""Главное к открытию четверга (31.10): Значение...",557,[],rdv,kaggle_russian_financial_news,text,сбербанк
308,kaggle_rfn_6417,GMKN,2024-10-28 10:31:47,NaN,"""​​Норильский никель: производство растет, но ...",625,['отчет'],t_invest,kaggle_russian_financial_news,text,норильский никель
661,kaggle_rfn_438,SBER,2024-07-10 14:56:33,NaN,"""️ Где искать новые ""Яндекс и Сбер""? #VIP_talk...",558,['VIPtalk'],rdv,kaggle_russian_financial_news,text,сбер
174,kaggle_rfn_81,GAZP,2024-08-29 15:06:15,NaN,"""️ Важно! Комментарий источника РДВ: Фактическ...",566,['аналитика'],rdv,kaggle_russian_financial_news,text,газпром
192,kaggle_rfn_6018,GAZP,2024-09-23 16:22:58,NaN,"""Блумберг уже видел проект бюджета РФ на следу...",252,['GAZP'],rdv,kaggle_russian_financial_news,text,газпром
352,kaggle_rfn_7372,NVTK,2024-05-06 06:44:14,NaN,"""Евросоюз остается главным покупателем российс...",2017,['новости'],t_invest,kaggle_russian_financial_news,text,новатэк
428,kaggle_rfn_10878,PLZL,2024-03-25 12:01:30,NaN,"""Ключевые события прошлой недели — в нашем дай...",778,['дайджест'],t_analytic,kaggle_russian_financial_news,text,полюс
109,kaggle_rfn_840,GAZP,2024-05-02 14:21:37,NaN,""" Интерфакс: Группа ""Газпром"" (GAZP) по итогам...",681,[],rdv,kaggle_russian_financial_news,text,газпром
1003,kaggle_rfn_6775,YDEX,2024-08-23 12:53:00,NaN,"""​​«Подумал, что это какое-то отложенное посту...",1647,[],t_invest,kaggle_russian_financial_news,text,yandex
290,kaggle_rfn_143,GMKN,2024-08-23 06:33:39,NaN,"""Главное к открытию пятницы (23.08): #брифинг ...",577,['брифинг'],rdv,kaggle_russian_financial_news,text,норникель
96,kaggle_rfn_7591,GAZP,2024-03-26 06:43:40,NaN,"""Газпром выкупит долю Shell в проекте Сахалин-...",2316,['новости'],t_invest,kaggle_russian_financial_news,text,газпром
538,kaggle_rfn_10740,ROSN,2024-09-05 15:51:07,NaN,"""Роснефть: все еще смотрим нейтрально Стабильн...",1967,['россия'],t_analytic,kaggle_russian_financial_news,text,роснефть
950,kaggle_rfn_428,YDEX,2024-07-12 06:31:33,NaN,"""Главное к открытию пятницы (12.07): #брифинг ...",780,['брифинг'],rdv,kaggle_russian_financial_news,text,yandex
178,kaggle_rfn_6722,GAZP,2024-08-30 13:21:56,NaN,"""О чем говорят инвесторы: падение Сегежи, силь...",3277,"['SGZH', 'MTLR', 'GAZP', 'NVTK', 'LKOH']",t_invest,kaggle_russian_financial_news,text,газпром
888,kaggle_rfn_7582,YDEX,2024-03-27 14:00:02,NaN,"""Биржевые фонды: почему это крутой актив и поч...",1291,"['подкаст', 'академияинвестиций']",t_invest,kaggle_russian_financial_news,text,яндекс

In [45]:
for ticker in sorted(news_for_llm["ticker"].unique()):
    print("\n" + "=" * 100)
    print(ticker)
    
    sample = news_for_llm[news_for_llm["ticker"] == ticker].sample(
        min(5, (news_for_llm["ticker"] == ticker).sum()),
        random_state=42,
    )
    
    for row in sample.itertuples(index=False):
        print("\n---")
        print("published_at:", row.published_at)
        print("matched_alias:", row.matched_alias)
        print("tags:", row.tags)
        print("text:", row.text[:500])

====================================================================================================
AFLT

---
published_at: 2024-11-06 08:20:40
matched_alias: аэрофлот
tags: ['новости']
text: " Make IMOEX Great Again Ралли на российском рынке после первых итогов выборов в США Официальные итоги на выборах в США еще не подведены, но Дональд Трамп уже объявил о своей победе и назвал себя 47-м президентом США, а заодно заявил, что намерен «не развязывать войны, а положить им конец». На российском рынке случилось ожидаемое «трампоралли» — индекс Московской биржи вырос на 3,61% и продолжает показывать позитивную динамику. Среди лидеров в акциях — АФК Система, Озон, Аэрофлот, Алроса, Газпро

---
published_at: 2024-11-29 11:58:00
matched_alias: аэрофлот
tags: ['отчет']
text: "​​Аэрофлот: выручка растет, но будут ли дивиденды? Крупнейший отечественный авиаперевозчик представил неоднозначные финансовые результаты по итогам третьего квартала 2024-го. Выручка Аэрофлота немного замедляется из-за высокой базы прошлого года, но продолжает показывать хорошие темпы роста. Ключевыми драйверами выступают увеличение пассажиропотока на 15% г/г и высокая загруженность кресел (более 92%), что вкупе с ростом доходов населения приводит к активному росту цен на авиабилеты. При этом с

---
published_at: 2024-01-04 11:48:00
matched_alias: аэрофлот
tags: []
text: "​​Жадный инвестор: лучшие выпуски 2023 года Весь прошлый год мы говорили с представителями разных компаний о том, как устроен их бизнес, благодаря чему они справляются с проблемами и показывают крутые финансовые результаты. Что важного мы узнали из этих интервью? Аэрофлот В какие страны планирует летать самый крупный российский авиаперевозчик? Как компания ремонтирует и обновляет парк в условиях санкций? Чем бизнесу помогло государство и почему сейчас Аэрофлот может обойтись без субсидий? Все э

---
published_at: 2024-09-11 06:36:35
matched_alias: аэрофлот
tags: ['новости']
text: "США расширили санкции против торгового флота РФ На что стоит обратить внимание сегодня Компании • Аэрофлот: публикация операционных результатов за август 2024 года. • Диасофт: внеочередное общее собрание акционеров. На повестке вопрос утверждения дивидендов за первое полугодие 2024 года. Ранее совет директоров компании рекомендовал выплатить дивиденды в размере 45 рублей на одну акцию. • ФосАгро: внеочередное общее собрание акционеров. На повестке вопрос утверждения дивидендов за первое полугод

---
published_at: 2024-02-12 12:54:59
matched_alias: аэрофлот
tags: ['отчет']
text: "​​️ Аэрофлот взлетает на отчете Крупнейший авиаперевозчик России подвел итоги четвертого квартала и всего 2023 года в отчете по форме РСБУ. В четвертом квартале 2023-го Аэрофлот продемонстрировал сокращение операционного убытка год к году и вышел в плюс по показателю чистой прибыли с учетом курсовой разницы. Последние годы бизнесу пришлось пережить несколько кризисов, связанных с ограничениями полетов. Однако Аэрофлот наращивает не только количество внутренних рейсов, но и планирует увеличивать

====================================================================================================
GAZP

---
published_at: 2024-11-22 12:49:02
matched_alias: газпром
tags: ['россия', 'идея']
text: "Наши актуальные рекомендации по российским акциям В этом посте мы собрали наши актуальные инвестидеи на рынке акций и указали рекомендации и таргеты на 12 месяцев для бумаг. Чтобы узнать больше о заинтересовавшей вас компании, перейдите по ссылке — там вы найдете наш разбор финансовых результатов, факторов инвестиционной привлекательности и рисков. Этот пост мы будем обновлять регулярно по мере выхода новых данных по компаниям и обновления наших взглядов на них. Рекомендация «покупать» Лукойл:

---
published_at: 2024-05-02 06:42:26
matched_alias: газпром
tags: ['новости']
text: "США ввели новые санкции в отношении юридических и физических лиц, связанных с Россией На что стоит обратить внимание сегодня Компании • Газпром: ожидается публикация финансовых результатов по МСФО за 2023 год. В 2022 году выручка компании по МСФО составила 11,7 трлн рублей (+14% год к году), а чистая прибыль сократилась до 1,3 трлн рублей (-39,2%). • ЭЛ5-Энерго: публикация финансовых результатов по МСФО за первый квартал 2024 года. По итогам первого квартала 2023 года выручка компании по МСФО у

---
published_at: 2024-07-24 06:38:54
matched_alias: газпром
tags: ['новости']
text: "Российским компаниям начнут компенсировать расходы на отечественное ПО На что стоит обратить внимание сегодня Компании • Старт торгов акциями МКПАО Яндекс под тикером YDEX после паузы, связанной с реструктуризацией и переездом компании в РФ. Бумаги входят в индекс российских технологий от Т-Капитал. После возобновления торгов управляющая компания начнет постепенно покупать акции Яндекса в наш фонд TITR. • ММК: заседание совета директоров. На повестке вопрос выплаты дивидендов за первое полугоди

---
published_at: 2024-05-27 06:36:11
matched_alias: газпром
tags: ['брифинг']
text: "Главное к открытию понедельника (27.05): #брифинг Значение индекса ЖиС: 54 (спокойствие). Подробнее об индексе здесь. 89.4 ₽/$, 12.3 ₽/¥, 82.2 $/барр., фьючерс на индекс Мосбиржи: +0.0% По итогам первых трех недель месяца поставки премиального сорта нефти ВСТО, который загружается на танкеры из порта Козьмино, выросли на 5% относительно среднего уровня апреля, до 960 тыс. баррелей в сутки. Предыдущий рекорд морских поставок нефти из Козьмино фиксировался в феврале, когда отгрузки превышали 914

---
published_at: 2024-08-31 10:39:12
matched_alias: газпром
tags: ['weekly']
text: " Самое важное за неделю. #weekly ️ Какие дивиденды могут заплатить Роснефть, Лукойл и Газпром за 1 полугодие 2024 ️ Правительство и ЦБ подготовят план действий по борьбе с инфляцией ️ Повышение ставки ЦБ отыграно некоторыми акциями ️ Динамика акций компаний, которые вышли на IPO в 2024 году ️ Падение добычи в РФ — одна из самых обсуждаемых тем у нефтяных аналитиков На этой неделе члены клуба зафиксировали прибыль +1.97% и +7.56% в двух шорт позициях — "

====================================================================================================
GMKN

---
published_at: 2024-01-29 06:43:00
matched_alias: норникель
tags: ['новости']
text: "Строительство «Силы Сибири — 2» может быть отложено На что стоит обратить внимание сегодня Компании • Норникель: публикация операционных результатов за четвертый квартал и двенадцать месяцев 2023 года. По итогам девяти месяцев 2023 года Норникель сообщал об увеличении производства палладия и платины на 1% и 7% соответственно при снижении производства никеля и меди на 9% и 4%. • Positive Technologies: предварительные данные по отгрузкам за 2023 год. По прогнозам компании, рост отгрузок по итогам

---
published_at: 2024-09-26 09:34:17
matched_alias: норникель
tags: ['мнение']
text: "Норникель (GMKN) — важнейший игрок на мировом рынке цветных металлов, напоминает источник РДВ. #мнение Норникель — одна из тех компаний, которая продолжает поставлять металл и в Европу, и в Северную Америку, несмотря на все санкционное давление, которое оказывается на российский экспорт. По итогам 2023 года на долю Европы и Северной Америки пришлось 34% выручки Норникеля. Ранее на этой неделе: Лондонская биржа цветных металлов сняла запрет на поставки никеля с финского завода Норникеля — в лишн

---
published_at: 2024-03-19 15:24:18
matched_alias: норникель
tags: ['государеводело', 'тактиканаРЦБ']
text: "️️️ Президент разрешил ПИФам продавать акции стратегических предприятий. #государево_дело #тактика_на_РЦБ В ПИФах акций на 368 млрд рублей. В смешанных ПИФах (где также могут быть акции) ещё 303 млрд рублей (по данным investfunds.ru). Ранее продажи акций стратегических компаний из ПИФов были запрещены из-за наличия среди инвесторов таких ПИФов нерезидентов. В списке стратегических компаний, чьи акции можно продавать: Аэрофлот (AFLT), Алроса (ALRS), Россети (FEES), Совкомфлот (FLOT), Газпром (GA

---
published_at: 2024-01-04 11:48:00
matched_alias: норильский никель
tags: []
text: "​​Жадный инвестор: лучшие выпуски 2023 года Весь прошлый год мы говорили с представителями разных компаний о том, как устроен их бизнес, благодаря чему они справляются с проблемами и показывают крутые финансовые результаты. Что важного мы узнали из этих интервью? Аэрофлот В какие страны планирует летать самый крупный российский авиаперевозчик? Как компания ремонтирует и обновляет парк в условиях санкций? Чем бизнесу помогло государство и почему сейчас Аэрофлот может обойтись без субсидий? Все э

---
published_at: 2024-04-22 11:14:37
matched_alias: норникель
tags: ['отчет']
text: "​​Норникель: производство ключевого металла сокращается В то время как цены на никель и медь растут Металлургический гигант опубликовал нейтральные производственные результаты за первый квартал 2024 года. Снижение выпуска никеля в первом квартале обусловлено ростом производства металла, который еще не прошел всех стадий обработки. В то же время объемы производства палладия в отчетном периоде были на высоком уровне. Аналитики Тинькофф Инвестиций пока нейтрально смотрят на акции компании, однако

====================================================================================================
NVTK

---
published_at: 2024-11-11 09:41:45
matched_alias: новатэк
tags: ['аналитика']
text: "Мультипликаторы российских нефтегазовых компаний. #аналитика Самая переоценённая акция в российском нефтегазе — Новатэк (NVTK), она оценена рынком в 5.1х годовых прибылей vs. медианные 3.8х. "

---
published_at: 2024-02-05 15:56:00
matched_alias: новатэк
tags: ['дайджест']
text: "Ключевые события прошлой недели — в нашем дайджесте. За чем следить на этой неделе Россия: - инфляция (за неделю); - обзор ставок на финансовом рынке (за январь); - уровень безработицы (за 2023 г.); - ВВП (за 2023 г.); - объем розничной торговли (за 2023 г.); - отчет Норникеля (за 2023 г.). Китай: потреб. и производственная инфляция (за январь). США: индексы деловой активности (PMI за январь); Еврозона: - розничные продажи (за декабрь 2023 г.); - инфляц. ожидания потребителей на следующие 12 ме

---
published_at: 2024-01-19 09:21:11
matched_alias: новатэк
tags: ['цифры']
text: "Топ-30 российских компаний по капитализации. По состоянию на 19 января 2024, в трлн руб. #цифры 1. Сбер (SBER, SBERP) 6.23 2. Роснефть (ROSN) 6.07 3. Лукойл (LKOH) 4.74 4. Новатэк (NVTK) 4.43 5. Газпромнефть (SIBN) 3.20 6. Газпром (GAZP) 3.93 7. Норникель (GMKN) 2.55 8. Татнефть (TATN, TATNP) 1.62 9. Полюс (PLZL) 1.49 10. Сургутнефтегаз (SNGS, SNGSP) 1.46 11. Северсталь (CHMF) 1.30 12. ВТБ (VTBR) 1.18 13. НЛМК (NLMK) 1.17 14. Транснефть (TRNFP) 1.12 15. Яндекс (YNDX) 0.93 16. Фосагро (PHOR) 0.8

---
published_at: 2024-09-23 06:28:12
matched_alias: новатэк
tags: ['новости']
text: "Евросоюз нарастил импорт российских удобрений в 2,2 раза На что стоит обратить внимание сегодня Компании • Solidcore Resources: последний торговый день в «стакане Т+1» акциями компании. Таким образом, сегодня последний день, когда можно продать бумаги Solidcore, — как обычно, в приложении, на сайте или в терминале. Валютные курсы (ЦБ РФ) USD/RUB: 92,58 (-0,12%). EUR/RUB: 103,38 (+0,12%). CNY/RUB: 13,04 (-0,46%). Товарно-сырьевой рынок (9:20) Urals: 70,29 (+0,49%). Brent: 74,26 (+0,54%). Золото:

---
published_at: 2024-11-01 06:33:46
matched_alias: новатэк
tags: ['новости']
text: "Экспорт СПГ из России в октябре достиг максимума с начала года На что стоит обратить внимание сегодня Компании • ЭЛ5-Энерго: публикация финансовых результатов по РСБУ за 9 месяцев 2024 года. Валютные курсы (ЦБ РФ) USD/RUB: 97,02 (-0,03%). EUR/RUB: 105,52 (+0,29%). CNY/RUB: 13,61 (+0,14%). Товарно-сырьевой рынок (9:30) Urals: 67,85 (+1,42%). Brent: 74,01 (+0,18%). Золото: 2 753,06 (+0,33%). Газ: 2,706 (-0,04%). Что еще • Российские СПГ-заводы по итогам октября отправили на экспорт рекордные с на

====================================================================================================
PLZL

---
published_at: 2024-11-25 16:03:50
matched_alias: полюс
tags: ['дайджест']
text: "Ключевые события прошлой недели — в нашем дайджесте. За чем следить на этой неделе Россия: - инфляция (за неделю); - ключевые экономические показатели, вкл. промпроизводство, розничные продажи, безработицу и рост реальных зарплат (за октябрь от Росстата); - предварительная оценка роста ВВП (за 3 кв. 2024 г. от Минэка). США: располагаемые доходы населения и потребительские расходы (за октябрь). Еврозона: потребительские и деловые настроения (за ноябрь). Идеи В акциях: - Полюс (таргет на 12 мес.

---
published_at: 2024-12-10 10:36:31
matched_alias: полюс
tags: ['новости']
text: "​​Проекты роста Полюса Компания собирается занять второе место в мире по производству золота Золотодобытчик поделился прогнозами по новым проектам, которые должны расширить бизнес компании. Первую линию фабрики на Сухом Логе Полюс планирует запустить в 2028 году, а вторую линию — в 2029-м. Проект предполагает производство 2,3—2,8 млн унций золота в год. Запуск этого месторождения увеличит добычу желтого металла в России более чем на 20%. Капитальные затраты составят $6 млрд. Совокупное производ

---
published_at: 2024-01-19 09:21:11
matched_alias: полюс
tags: ['цифры']
text: "Топ-30 российских компаний по капитализации. По состоянию на 19 января 2024, в трлн руб. #цифры 1. Сбер (SBER, SBERP) 6.23 2. Роснефть (ROSN) 6.07 3. Лукойл (LKOH) 4.74 4. Новатэк (NVTK) 4.43 5. Газпромнефть (SIBN) 3.20 6. Газпром (GAZP) 3.93 7. Норникель (GMKN) 2.55 8. Татнефть (TATN, TATNP) 1.62 9. Полюс (PLZL) 1.49 10. Сургутнефтегаз (SNGS, SNGSP) 1.46 11. Северсталь (CHMF) 1.30 12. ВТБ (VTBR) 1.18 13. НЛМК (NLMK) 1.17 14. Транснефть (TRNFP) 1.12 15. Яндекс (YNDX) 0.93 16. Фосагро (PHOR) 0.8

---
published_at: 2024-10-28 13:43:54
matched_alias: полюс
tags: ['дайджест']
text: "Ключевые события прошлой недели — в нашем дайджесте. За чем следить на этой неделе Россия: - экономическая активность в России, включая динамику потребительского спроса и рынка труда (за сентябрь от Росстата); - инфляция (за неделю); - финансовые отчеты Яндекса и Сбера за 3 кв. 2024 г. Китай: индексы деловой активности (PMI за октябрь). США: - оценка роста ВВП (за 3 кв. 2024 г.); - оценка базовой инфляции (за сентябрь); - уровень безработицы (за октябрь); - индексы деловой активности (PMI за ок

---
published_at: 2024-02-29 15:21:16
matched_alias: полюс
tags: ['россия', 'идея']
text: "​​Полюс: сильные финансовые результаты, но дивиденды под вопросом Золотодобытчик опубликовал результаты второго полугодия и всего 2023 года. Во втором полугодии объемы производства золота остались на уровне первого полугодия. Однако объемы реализации выросли на 31% п/п благодаря распродаже запасов, накопленных в первом полугодии. На этом фоне, а также ввиду роста цен на золото выручка во втором полугодии выросла на 28% п/п, а маржинальность по скорректированной EBITDA составила 72% (в первом по

====================================================================================================
ROSN

---
published_at: 2024-04-24 07:56:51
matched_alias: роснефть
tags: ['аналитика']
text: " Globaltrans (GLTR): разбор компании. #аналитика Globaltrans - одна из крупнейших в России компаний в сфере грузовых ж/д перевозок на территории России и стран СНГ. По размеру парка в оперировании компания занимает четвертое место среди операторов подвижного состава в России, примерно 5% от общероссийского парка. Основной бизнес Globaltrans — предоставление услуг по ж/д перевозкам грузов и аренде вагонов. Общий парк Globaltrans включает около 66 тысяч единиц подвижного состава, 94% общего парка

---
published_at: 2024-01-10 06:49:00
matched_alias: роснефть
tags: ['новости']
text: "Всемирный банк улучшил прогноз экономического роста России на 2024 год На что стоит обратить внимание сегодня Компании • Магнит: последний день для попадания в реестр акционеров, имеющих право на получение дивидендов из ранее нераспределенной прибыли (412,13 рубля на акцию). • Роснефть: последний день для попадания в реестр акционеров, имеющих право на получение дивидендов за девять месяцев 2023 года (30,77 рубля на акцию). Фьючерсы (9:30) Сегодня утром фьючерсы на индекс Мосбиржи (-0,23%) сниж

---
published_at: 2024-03-28 06:30:01
matched_alias: роснефть
tags: ['брифинг']
text: "Главное к открытию четверга (27.03): #брифинг Значение индекса ЖиС: 71 (жадность). Подробнее об индексе здесь. 92.0 ₽/$, 12.6 ₽/¥, 85.8 $/барр., фьючерс на индекс Мосбиржи: +0.02% Алроса и Минфин заключили соглашение о выкупе части произведенного алмазного сырья в 2024 году. В рамках этого договора Гохран в марте этого года приобрел у Алросы первую партию алмазов, включающую весь срез добычи. Добыча угля в России в феврале 2024 снизилась на 0.7% г/г до 34.6 млн т. Это минимальный месячный объем

---
published_at: 2024-05-17 14:22:58
matched_alias: роснефть
tags: ['мнение']
text: "️ Юнипро (UPRO) дивидендов не будет "ближайшие лет 5, а то и больше". Ожидания рынка от Юнипро сильно перегреты. #мнение Почему Юнипро не будет платить дивиденды в будущем (по крайней мере, ближайшие 5 лет)? ️ В будущем Юнипро может быть конфисковано в пользу Роснефти, в случае если немецкое правительство национализирует НПЗ Роснефти в Германии. ️ Исторически, Роснефть стремится максимизировать дивиденды для своих акционеров, а не для акционеров дочерних компаний. Похожий подход к дивидендам до

---
published_at: 2024-03-15 15:03:37
matched_alias: роснефть
tags: ['цифры']
text: "Топ-30 российских компаний по капитализации. По состоянию на 15 марта 2024, в трлн руб. #цифры 1. Сбер (SBER, SBERP) 6.68 2. Роснефть (ROSN) 6.19 3. Лукойл (LKOH) 5.11 4. Новатэк (NVTK) 4.25 5. Газпромнефть (SIBN) 3.84 6. Газпром (GAZP) 3.81 7. Норникель (GMKN) 2.31 8. Татнефть (TATN, TATNP) 1.74 9. Полюс (PLZL) 1.60 10. Сургутнефтегаз (SNGS, SNGSP) 1.51 11. Северсталь (CHMF) 1.43 12. НЛМК (NLMK) 1.23 13. Яндекс (YNDX) 1.18 14. Транснефть (TRNFP) 1.15 15. ВТБ (VTBR) 1.14 16. Фосагро (PHOR) 0.87

====================================================================================================
SBER

---
published_at: 2024-02-09 08:49:00
matched_alias: сбербанк
tags: ['отчет']
text: "​​Высокая ключевая ставка начинает влиять на результаты Сбера Сбербанк опубликовал отчет РПБУ с итогами первого месяца 2024 года. Год к году показатель чистой прибыли вырос. Однако месяц к месяцу рост незначительно замедлился: в декабре 2023-го самый крупный банк России заработал 115,6 млрд против 115,1 млрд в январе. Комментарий аналитика Тинькофф Инвестиций Ляйсян Хусяиновой, CFA: Месячное значение прибыли за январь осталось на уровне последних месяцев 2023 года. Продолжается замедление темпо

---
published_at: 2024-03-15 15:03:37
matched_alias: сбер
tags: ['цифры']
text: "Топ-30 российских компаний по капитализации. По состоянию на 15 марта 2024, в трлн руб. #цифры 1. Сбер (SBER, SBERP) 6.68 2. Роснефть (ROSN) 6.19 3. Лукойл (LKOH) 5.11 4. Новатэк (NVTK) 4.25 5. Газпромнефть (SIBN) 3.84 6. Газпром (GAZP) 3.81 7. Норникель (GMKN) 2.31 8. Татнефть (TATN, TATNP) 1.74 9. Полюс (PLZL) 1.60 10. Сургутнефтегаз (SNGS, SNGSP) 1.51 11. Северсталь (CHMF) 1.43 12. НЛМК (NLMK) 1.23 13. Яндекс (YNDX) 1.18 14. Транснефть (TRNFP) 1.15 15. ВТБ (VTBR) 1.14 16. Фосагро (PHOR) 0.87

---
published_at: 2024-10-31 07:07:20
matched_alias: сбер
tags: ['отчет']
text: "​​Отчет Сбербанка: каких дивидендов ждать в следующем году? Сбер опубликовал финансовый отчет за третий квартал и девять месяцев 2024 года. Показатель квартальной чистой прибыли самого крупного банка в России незначительно снизился. На ее динамику повлиял эффект переоценки отложенных налоговых обязательств от ожидаемого повышения налога на прибыль в 2025 году. Динамика потребительского кредитования продолжает замедляться. При этом темпы роста корпоративных кредитов все еще остаются на высоком у

---
published_at: 2024-06-13 06:39:17
matched_alias: сбер
tags: ['новости']

In [46]:
from pathlib import Path
import pandas as pd
import json

DATA_DIR = Path("../data/external/kaggle/russian_financial_news/RussianFinancialNews")

news_path = DATA_DIR / "news_collection.parquet"
gpt4o_path = DATA_DIR / "news_descriptions" / "news_descriptions_GPT4o.json"
llama_path = DATA_DIR / "news_descriptions" / "news_description_Llama3_8b.json"

news = pd.read_parquet(news_path)

with open(gpt4o_path, "r", encoding="utf-8") as f:
    gpt4o_data = json.load(f)

with open(llama_path, "r", encoding="utf-8") as f:
    llama_data = json.load(f)

print("news:", news.shape)
print("gpt4o type:", type(gpt4o_data))
print("llama type:", type(llama_data))

news: (91955, 6)
gpt4o type: <class 'dict'>
llama type: <class 'dict'>

In [47]:
if isinstance(gpt4o_data, dict):
    print("gpt4o dict length:", len(gpt4o_data))
    first_key = next(iter(gpt4o_data))
    print("first key:", first_key)
    print("first value:", gpt4o_data[first_key])

elif isinstance(gpt4o_data, list):
    print("gpt4o list length:", len(gpt4o_data))
    print("first item:", gpt4o_data[0])

gpt4o dict length: 15000
first key: 0
first value: {'thinking': "The article discusses Gazprom's production figures, highlighting a discrepancy between gas and oil revenue, and mentioning potential market changes in Russia's energy strategy. This is a financial report as it concerns company performance metrics (revenue figures) and an upcoming policy decision that could affect the gas market.", 'article_type': 'finance', 'country': ['Russia'], 'sectors': ['Energy'], 'tickers': ['GAZP'], 'sentiment_score': -0.5}

In [48]:
if isinstance(llama_data, dict):
    print("llama dict length:", len(llama_data))
    first_key = next(iter(llama_data))
    print("first key:", first_key)
    print("first value:", llama_data[first_key])

elif isinstance(llama_data, list):
    print("llama list length:", len(llama_data))
    print("first item:", llama_data[0])

llama dict length: 24398
first key: 0
first value: {'thinking': "The article discusses the recent trend in Gazprom's oil and gas production, highlighting that despite a significant increase in natural gas extraction, the revenue from gas sales has decreased compared to oil sales. This could potentially impact Russia's energy market and the country's overall economy.", 'description': {'article_type': 'finance', 'country': ['Russia'], 'sectors': ['Energy'], 'tickers': ['GAZP'], 'sentiment_score': -0.5}}

In [49]:
from pathlib import Path
import pandas as pd

events_path = Path("../data/interim/news/news_events_precomputed_llm_2024.parquet")

events = pd.read_parquet(events_path)

print(events.shape)
print(events.columns.tolist())

print("\nSentiment coverage:")
print("with sentiment:", events["sentiment_score"].notna().sum())
print("missing sentiment:", events["sentiment_score"].isna().sum())

print("\nRows by ticker:")
print(events["ticker"].value_counts().sort_index())

print("\nLLM model:")
print(events["llm_model"].value_counts(dropna=False))

print("\nArticle types:")
print(events["article_type"].value_counts(dropna=False).head(20))

print("\nSentiment score:")
print(events["sentiment_score"].describe())

display(events.sample(20, random_state=42))

(1060, 17)
['news_id', 'raw_news_id', 'ticker', 'published_at', 'text', 'tags', 'source', 'matched_alias', 'match_type', 'article_type', 'sectors', 'llm_tickers', 'sentiment_score', 'impact_score', 'confidence', 'reason', 'llm_model']

Sentiment coverage:
with sentiment: 996
missing sentiment: 64

Rows by ticker:
ticker
AFLT     65
GAZP    173
GMKN     74
NVTK    106
PLZL     65
ROSN     82
SBER    180
TATN     63
VKCO      6
YDEX    246
Name: count, dtype: int64

LLM model:
llm_model
llama3_8b    1060
Name: count, dtype: int64

Article types:
article_type
finance        936
NaN             64
opinions        32
others          11
advertising     11
politics         6
Name: count, dtype: int64

Sentiment score:
count    996.000000
mean       0.169920
std        0.602765
min       -1.000000
25%        0.000000
50%        0.000000
75%        0.500000
max        1.000000
Name: sentiment_score, dtype: float64

,news_id,raw_news_id,ticker,published_at,text,tags,source,matched_alias,match_type,article_type,sectors,llm_tickers,sentiment_score,impact_score,confidence,reason,llm_model
972,kaggle_rfn_322,322,YDEX,2024-07-25 12:04:44,""" Самолет Плюс сейчас — это Яндекс.Такси или U...",['VIPtalk'],rdv,яндекс,text,finance,"[Technology, Financial Services]",[YDEX],0.0,0.0,1.0,The article discusses financial events affecti...,llama3_8b
312,kaggle_rfn_7982,7982,NVTK,2024-01-09 06:45:00,"""Российские банки выходят на рынок Индии, а ЦБ...",['новости'],t_invest,новатэк,text,finance,[Financial Service],"[SBER, MTSS, FGFN, ROSST]",0.0,0.0,1.0,This article focuses on financial events relev...,llama3_8b
70,kaggle_rfn_7897,7897,GAZP,2024-01-29 06:43:00,"""Строительство «Силы Сибири — 2» может быть от...",['новости'],t_invest,газпром,text,finance,[Transportation],[TKTR],-1.0,-1.0,1.0,The article reports on the financial performan...,llama3_8b
1028,kaggle_rfn_6556,6556,YDEX,2024-10-03 15:45:00,"""​​Какие акции стоит купить прямо сейчас? Онла...",[],t_invest,яндекс,text,finance,"[Basic Materials, Energy]",None,1.0,1.0,1.0,The article discusses the completion of explor...,llama3_8b
1021,kaggle_rfn_10728,10728,YDEX,2024-09-21 08:24:32,"""Металлурги и дивиденды В эфире подкаст Жадный...",[],t_analytic,яндекс,text,finance,[Basic Materials],[NLMM],0.0,0.0,1.0,The article presents financial results of NLMK...,llama3_8b
716,kaggle_rfn_5754,5754,SBER,2024-10-31 06:34:29,"""Главное к открытию четверга (31.10): Значение...",[],rdv,сбербанк,text,finance,None,None,-0.5,-0.5,1.0,The article provides statistical data on the v...,llama3_8b
308,kaggle_rfn_6417,6417,GMKN,2024-10-28 10:31:47,"""​​Норильский никель: производство растет, но ...",['отчет'],t_invest,норильский никель,text,finance,"[Consumer Cyclical, Real Estate]",[],0.0,0.0,1.0,The article reports on the approval of a divid...,llama3_8b
661,kaggle_rfn_438,438,SBER,2024-07-10 14:56:33,"""️ Где искать новые ""Яндекс и Сбер""? #VIP_talk...",['VIPtalk'],rdv,сбер,text,finance,[Technology],"[ASTR, SBER, MTSS, TATN]",1.0,1.0,1.0,The article provides an analysis of Astra's (A...,llama3_8b
174,kaggle_rfn_81,81,GAZP,2024-08-29 15:06:15,"""️ Важно! Комментарий источника РДВ: Фактическ...",['аналитика'],rdv,газпром,text,finance,[Energy],"[$RSPO, $Gazprom]",-0.5,-0.5,1.0,The article provides an analysis of Gazprom's ...,llama3_8b
192,kaggle_rfn_6018,6018,GAZP,2024-09-23 16:22:58,"""Блумберг уже видел проект бюджета РФ на следу...",['GAZP'],rdv,газпром,text,finance,[Financial Service],[],-1.0,-1.0,1.0,The article discusses a warning from the U.S. ...,llama3_8b
352,kaggle_rfn_7372,7372,NVTK,2024-05-06 06:44:14,"""Евросоюз остается главным покупателем российс...",['новости'],t_invest,новатэк,text,finance,[Transportation],None,1.0,1.0,1.0,The article is discussing the growth metrics o...,llama3_8b
428,kaggle_rfn_10878,10878,PLZL,2024-03-25 12:01:30,"""Ключевые события прошлой недели — в нашем дай...",['дайджест'],t_analytic,полюс,text,finance,"[Consumer Cyclical, Energy, Utilities]","[MGNT, TATN, MGLB, ASMN, ALRO]",0.0,0.0,1.0,The article primarily discusses financial even...,llama3_8b
109,kaggle_rfn_840,840,GAZP,2024-05-02 14:21:37,""" Интерфакс: Группа ""Газпром"" (GAZP) по итогам...",[],rdv,газпром,text,finance,[Financial Service],[LSRG],-0.2,-0.2,1.0,The article primarily deals with financial new...,llama3_8b
1003,kaggle_rfn_6775,6775,YDEX,2024-08-23 12:53:00,"""​​«Подумал, что это какое-то отложенное посту...",[],t_invest,yandex,text,finance,[Basic Materials],[VSMP],0.5,0.5,1.0,The article is a financial report on the reven...,llama3_8b
290,kaggle_rfn_143,143,GMKN,2024-08-23 06:33:39,"""Главное к открытию пятницы (23.08): #брифинг ...",['брифинг'],rdv,норникель,text,advertising,None,None,1.0,1.0,1.0,The article is essentially an advertisement fo...,llama3_8b
96,kaggle_rfn_7591,7591,GAZP,2024-03-26 06:43:40,"""Газпром выкупит долю Shell в проекте Сахалин-...",['новости'],t_invest,газпром,text,finance,"[Аgriculture, Consumer Cyclical, Energy]",None,1.0,1.0,1.0,The article discusses Russia's plans for expor...,llama3_8b
538,kaggle_rfn_10740,10740,ROSN,2024-09-05 15:51:07,"""Роснефть: все еще смотрим нейтрально Стабильн...",['россия'],t_analytic,роснефть,text,finance,[Industrials],[],1.0,1.0,1.0,This article highlights FESCO's improvement in...,llama3_8b
950,kaggle_rfn_428,428,YDEX,2024-07-12 06:31:33,"""Главное к открытию пятницы (12.07): #брифинг ...",['брифинг'],rdv,yandex,text,finance,"[Technology, Financial Service]","[SBER, MTSS, TATN]",0.8,0.8,1.0,The article appears to be providing a statisti...,llama3_8b
178,kaggle_rfn_6722,6722,GAZP,2024-08-30 13:21:56,"""О чем говорят инвесторы: падение Сегежи, силь...","['SGZH', 'MTLR', 'GAZP', 'NVTK', 'LKOH']",t_invest,газпром,text,NaN,None,None,NaN,NaN,0.0,The article discusses the current trends and e...,llama3_8b
888,kaggle_rfn_7582,7582,YDEX,2024-03-27 14:00:02,"""Биржевые фонды: почему это крутой актив и поч...","['подкаст', 'академияинвестиций']",t_invest,яндекс,text,finance,None,None,1.0,1.0,1.0,The article comes from a financial report deta...,llama3_8b

In [50]:
from pathlib import Path
import pandas as pd

structured_path = Path("../data/interim/news/news_events_structured_2024.parquet")

structured = pd.read_parquet(structured_path)

print(structured.shape)

print("\nEvent types:")
print(structured["event_type"].value_counts(dropna=False))

print("\nSentiment:")
print(structured["sentiment_label"].value_counts(dropna=False))

print("\nTicker x Event type:")
display(pd.crosstab(structured["ticker"], structured["event_type"]))

display(
    structured[
        [
            "ticker",
            "published_at",
            "event_type",
            "sentiment_label",
            "sentiment_score",
            "text",
            "reason",
        ]
    ].sample(20, random_state=42)
)

(1060, 20)

Event types:
event_type
dividends            498
earnings             232
debt                  64
mna                   52
sanctions             45
other                 40
production            39
macro                 27
forecast              27
market_commentary     18
legal                 13
management             5
Name: count, dtype: int64

Sentiment:
sentiment_label
neutral     397
positive    393
negative    206
unknown      64
Name: count, dtype: int64

Ticker x Event type:

event_type,debt,dividends,earnings,forecast,legal,macro,management,market_commentary,mna,other,production,sanctions
ticker,,,,,,,,,,,,
AFLT,3,26,22,0,1,4,1,3,2,0,1,2
GAZP,6,93,36,4,2,5,0,0,5,6,8,8
GMKN,4,38,18,0,0,2,0,0,3,3,2,4
NVTK,3,37,28,5,0,1,0,3,1,9,1,18
PLZL,7,33,11,2,0,1,0,0,4,4,2,1
ROSN,3,43,14,2,1,3,0,1,4,3,5,3
SBER,13,102,41,1,4,2,0,2,7,4,4,0
TATN,2,45,5,0,0,2,0,1,3,3,1,1
VKCO,2,1,1,0,1,0,0,0,1,0,0,0
YDEX,21,80,56,13,4,7,4,8,22,8,15,8

,ticker,published_at,event_type,sentiment_label,sentiment_score,text,reason
972,YDEX,2024-07-25 12:04:44,market_commentary,neutral,0.0,""" Самолет Плюс сейчас — это Яндекс.Такси или U...",The article discusses financial events affecti...
312,NVTK,2024-01-09 06:45:00,dividends,neutral,0.0,"""Российские банки выходят на рынок Индии, а ЦБ...",This article focuses on financial events relev...
70,GAZP,2024-01-29 06:43:00,earnings,negative,-1.0,"""Строительство «Силы Сибири — 2» может быть от...",The article reports on the financial performan...
1028,YDEX,2024-10-03 15:45:00,macro,positive,1.0,"""​​Какие акции стоит купить прямо сейчас? Онла...",The article discusses the completion of explor...
1021,YDEX,2024-09-21 08:24:32,dividends,neutral,0.0,"""Металлурги и дивиденды В эфире подкаст Жадный...",The article presents financial results of NLMK...
716,SBER,2024-10-31 06:34:29,earnings,negative,-0.5,"""Главное к открытию четверга (31.10): Значение...",The article provides statistical data on the v...
308,GMKN,2024-10-28 10:31:47,dividends,neutral,0.0,"""​​Норильский никель: производство растет, но ...",The article reports on the approval of a divid...
661,SBER,2024-07-10 14:56:33,legal,positive,1.0,"""️ Где искать новые ""Яндекс и Сбер""? #VIP_talk...",The article provides an analysis of Astra's (A...
174,GAZP,2024-08-29 15:06:15,dividends,negative,-0.5,"""️ Важно! Комментарий источника РДВ: Фактическ...",The article provides an analysis of Gazprom's ...
192,GAZP,2024-09-23 16:22:58,other,negative,-1.0,"""Блумберг уже видел проект бюджета РФ на следу...",The article discusses a warning from the U.S. ...
352,NVTK,2024-05-06 06:44:14,dividends,positive,1.0,"""Евросоюз остается главным покупателем российс...",The article is discussing the growth metrics o...
428,PLZL,2024-03-25 12:01:30,earnings,neutral,0.0,"""Ключевые события прошлой недели — в нашем дай...",The article primarily discusses financial even...
109,GAZP,2024-05-02 14:21:37,dividends,negative,-0.2,""" Интерфакс: Группа ""Газпром"" (GAZP) по итогам...",The article primarily deals with financial new...
1003,YDEX,2024-08-23 12:53:00,debt,positive,0.5,"""​​«Подумал, что это какое-то отложенное посту...",The article is a financial report on the reven...
290,GMKN,2024-08-23 06:33:39,earnings,positive,1.0,"""Главное к открытию пятницы (23.08): #брифинг ...",The article is essentially an advertisement fo...
96,GAZP,2024-03-26 06:43:40,earnings,positive,1.0,"""Газпром выкупит долю Shell в проекте Сахалин-...",The article discusses Russia's plans for expor...
538,ROSN,2024-09-05 15:51:07,dividends,positive,1.0,"""Роснефть: все еще смотрим нейтрально Стабильн...",This article highlights FESCO's improvement in...
950,YDEX,2024-07-12 06:31:33,dividends,positive,0.8,"""Главное к открытию пятницы (12.07): #брифинг ...",The article appears to be providing a statisti...
178,GAZP,2024-08-30 13:21:56,dividends,unknown,NaN,"""О чем говорят инвесторы: падение Сегежи, силь...",The article discusses the current trends and e...
888,YDEX,2024-03-27 14:00:02,dividends,positive,1.0,"""Биржевые фонды: почему это крутой актив и поч...",The article comes from a financial report deta...

In [51]:
from pathlib import Path
import pandas as pd

features_path = Path("../data/processed/news/news_features_hourly_2024.parquet")

features = pd.read_parquet(features_path)

print(features.shape)
print(features["datetime"].min())
print(features["datetime"].max())
print(features["ticker"].value_counts().sort_index())

print("\nColumns:")
print(features.columns.tolist())

print("\nNon-zero rows:")
print("1h:", (features["news_count_1h"] > 0).sum())
print("6h:", (features["news_count_6h"] > 0).sum())
print("24h:", (features["news_count_24h"] > 0).sum())
print("72h:", (features["news_count_72h"] > 0).sum())

display(features.sample(20, random_state=42))

(34384, 82)
2024-01-03 09:00:00
2024-12-13 23:00:00
ticker
AFLT    3656
GAZP    3656
GMKN    3594
NVTK    3656
PLZL    3656
ROSN    3656
SBER    3656
TATN    3656
VKCO    3656
YDEX    1542
Name: count, dtype: int64

Columns:
['datetime', 'ticker', 'news_count_1h', 'sentiment_avg_1h', 'impact_avg_1h', 'impact_abs_max_1h', 'positive_count_1h', 'negative_count_1h', 'neutral_count_1h', 'unknown_count_1h', 'dividends_count_1h', 'earnings_count_1h', 'debt_count_1h', 'sanctions_count_1h', 'production_count_1h', 'mna_count_1h', 'management_count_1h', 'forecast_count_1h', 'market_commentary_count_1h', 'macro_count_1h', 'legal_count_1h', 'other_count_1h', 'news_count_6h', 'sentiment_avg_6h', 'impact_avg_6h', 'impact_abs_max_6h', 'positive_count_6h', 'negative_count_6h', 'neutral_count_6h', 'unknown_count_6h', 'dividends_count_6h', 'earnings_count_6h', 'debt_count_6h', 'sanctions_count_6h', 'production_count_6h', 'mna_count_6h', 'management_count_6h', 'forecast_count_6h', 'market_commentary_count_6h', 'macro_count_6h', 'legal_count_6h', 'other_count_6h', 'news_count_24h', 'sentiment_avg_24h', 'impact_avg_24h', 'impact_abs_max_24h', 'positive_count_24h', 'negative_count_24h', 'neutral_count_24h', 'unknown_count_24h', 'dividends_count_24h', 'earnings_count_24h', 'debt_count_24h', 'sanctions_count_24h', 'production_count_24h', 'mna_count_24h', 'management_count_24h', 'forecast_count_24h', 'market_commentary_count_24h', 'macro_count_24h', 'legal_count_24h', 'other_count_24h', 'news_count_72h', 'sentiment_avg_72h', 'impact_avg_72h', 'impact_abs_max_72h', 'positive_count_72h', 'negative_count_72h', 'neutral_count_72h', 'unknown_count_72h', 'dividends_count_72h', 'earnings_count_72h', 'debt_count_72h', 'sanctions_count_72h', 'production_count_72h', 'mna_count_72h', 'management_count_72h', 'forecast_count_72h', 'market_commentary_count_72h', 'macro_count_72h', 'legal_count_72h', 'other_count_72h']

Non-zero rows:
1h: 502
6h: 3422
24h: 7591
72h: 13928

,datetime,ticker,news_count_1h,sentiment_avg_1h,impact_avg_1h,impact_abs_max_1h,positive_count_1h,negative_count_1h,neutral_count_1h,unknown_count_1h,...,debt_count_72h,sanctions_count_72h,production_count_72h,mna_count_72h,management_count_72h,forecast_count_72h,market_commentary_count_72h,macro_count_72h,legal_count_72h,other_count_72h
25668,2024-01-16 12:00:00,TATN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16435,2024-07-01 23:00:00,PLZL,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
29462,2024-01-29 15:00:00,VKCO,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
17720,2024-10-29 18:00:00,PLZL,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12073,2024-04-23 22:00:00,NVTK,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12451,2024-05-30 10:00:00,NVTK,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
25951,2024-02-12 10:00:00,TATN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
16852,2024-08-08 20:00:00,PLZL,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6134,2024-08-27 13:00:00,GAZP,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
18486,2024-01-26 22:00:00,ROSN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
14632,2024-01-09 19:00:00,PLZL,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11044,2024-01-16 12:00:00,NVTK,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
31697,2024-08-29 16:00:00,VKCO,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11327,2024-02-12 10:00:00,NVTK,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
12757,2024-06-28 16:00:00,NVTK,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3806,2024-01-17 09:00:00,GAZP,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
33051,2024-08-12 23:00:00,YDEX,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
29341,2024-01-17 14:00:00,VKCO,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10175,2024-10-08 10:00:00,GMKN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7364,2024-01-08 16:00:00,GMKN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [52]:
sber_features = features[
    (features["ticker"] == "SBER") &
    (features["news_count_24h"] > 0)
].copy()

print(sber_features.shape)

display(
    sber_features[
        [
            "datetime",
            "ticker",
            "news_count_24h",
            "sentiment_avg_24h",
            "impact_avg_24h",
            "impact_abs_max_24h",
            "dividends_count_24h",
            "earnings_count_24h",
            "negative_count_24h",
            "positive_count_24h",
        ]
    ].head(30)
)

(1402, 82)

,datetime,ticker,news_count_24h,sentiment_avg_24h,impact_avg_24h,impact_abs_max_24h,dividends_count_24h,earnings_count_24h,negative_count_24h,positive_count_24h
21934,2024-01-09 09:00:00,SBER,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
21935,2024-01-09 10:00:00,SBER,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
21936,2024-01-09 11:00:00,SBER,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
21937,2024-01-09 12:00:00,SBER,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
21938,2024-01-09 13:00:00,SBER,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
21939,2024-01-09 14:00:00,SBER,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
21940,2024-01-09 15:00:00,SBER,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
21941,2024-01-09 16:00:00,SBER,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
21942,2024-01-09 17:00:00,SBER,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
21943,2024-01-09 18:00:00,SBER,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
21944,2024-01-09 19:00:00,SBER,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
21945,2024-01-09 20:00:00,SBER,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
21946,2024-01-09 21:00:00,SBER,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
21947,2024-01-09 22:00:00,SBER,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
21948,2024-01-09 23:00:00,SBER,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
21955,2024-01-10 15:00:00,SBER,1.0,1.0,1.0,1.0,0.0,1.0,0.0,1.0
21956,2024-01-10 16:00:00,SBER,1.0,1.0,1.0,1.0,0.0,1.0,0.0,1.0
21957,2024-01-10 17:00:00,SBER,1.0,1.0,1.0,1.0,0.0,1.0,0.0,1.0
21958,2024-01-10 18:00:00,SBER,1.0,1.0,1.0,1.0,0.0,1.0,0.0,1.0
21959,2024-01-10 19:00:00,SBER,1.0,1.0,1.0,1.0,0.0,1.0,0.0,1.0
21960,2024-01-10 20:00:00,SBER,1.0,1.0,1.0,1.0,0.0,1.0,0.0,1.0
21961,2024-01-10 21:00:00,SBER,1.0,1.0,1.0,1.0,0.0,1.0,0.0,1.0
21962,2024-01-10 22:00:00,SBER,1.0,1.0,1.0,1.0,0.0,1.0,0.0,1.0
21963,2024-01-10 23:00:00,SBER,1.0,1.0,1.0,1.0,0.0,1.0,0.0,1.0
21964,2024-01-11 09:00:00,SBER,1.0,1.0,1.0,1.0,0.0,1.0,0.0,1.0
21965,2024-01-11 10:00:00,SBER,1.0,1.0,1.0,1.0,0.0,1.0,0.0,1.0
21966,2024-01-11 11:00:00,SBER,1.0,1.0,1.0,1.0,0.0,1.0,0.0,1.0
21967,2024-01-11 12:00:00,SBER,1.0,1.0,1.0,1.0,0.0,1.0,0.0,1.0
21968,2024-01-11 13:00:00,SBER,1.0,1.0,1.0,1.0,0.0,1.0,0.0,1.0
21969,2024-01-11 14:00:00,SBER,1.0,1.0,1.0,1.0,0.0,1.0,0.0,1.0

In [53]:
features = pd.read_parquet("../data/processed/news/news_features_hourly_2024.parquet")

print(features.shape)
print(features["ticker"].value_counts().sort_index())

print("non-zero rows:")
print("1h:", (features["news_count_1h"] > 0).sum())
print("6h:", (features["news_count_6h"] > 0).sum())
print("24h:", (features["news_count_24h"] > 0).sum())
print("72h:", (features["news_count_72h"] > 0).sum())

(34384, 82)
ticker
AFLT    3656
GAZP    3656
GMKN    3594
NVTK    3656
PLZL    3656
ROSN    3656
SBER    3656
TATN    3656
VKCO    3656
YDEX    1542
Name: count, dtype: int64
non-zero rows:
1h: 502
6h: 3422
24h: 7591
72h: 13928